---
permalink: sg6000/configuring-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Depois de aplicar energia ao aparelho, você deve configurar as conexões de rede que serão usadas pelo StorageGRID. É necessário configurar o Gerenciador de sistemas do SANtricity, que é o software que você usará para monitorar as controladoras de storage e outro hardware no compartimento da controladora. Você também deve garantir que você pode acessar a interface BMC para o controlador SG6000-CN. 
---
= Configurar o hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de aplicar energia ao aparelho, você deve configurar as conexões de rede que serão usadas pelo StorageGRID. É necessário configurar o Gerenciador de sistemas do SANtricity, que é o software que você usará para monitorar as controladoras de storage e outro hardware no compartimento da controladora. Você também deve garantir que você pode acessar a interface BMC para o controlador SG6000-CN.

.Passos
* link:configuring-storagegrid-connections.html["Configurando conexões StorageGRID"]
* link:accessing-and-configuring-santricity-system-manager.html["Acessando e configurando o Gerenciador do sistema do SANtricity"]
* link:configuring-bmc-interface-sg6000.html["Configurando a interface BMC"]
* link:optional-enabling-node-encryption.html["Opcional: Habilitando a criptografia de nó"]
* link:optional-changing-raid-mode-sg6000-only.html["Opcional: Alterar o modo RAID (apenas SG6000)"]
* link:optional-remapping-network-ports-for-appliance-sg6000.html["Opcional: Remapeamento de portas de rede para o dispositivo"]

