---
permalink: sg6000/configuring-bmc-interface-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up 
summary: 'A interface do usuário para o controlador de gerenciamento de placa base (BMC) no controlador SG6000-CN fornece informações de status sobre o hardware e permite que você configure as configurações SNMP e outras opções para o controlador SG6000-CN.' 
---
= Configurando a interface BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A interface do usuário do controlador de gerenciamento de placa base (BMC) no controlador SG6000-CN fornece informações de status sobre o hardware e permite configurar configurações SNMP e outras opções para o controlador SG6000-CN.

.Passos
* link:changing-root-password-for-bmc-interface-sg6000.html["Alterar a senha raiz da interface BMC"]
* link:setting-ip-address-for-bmc-management-port-sg6000.html["Definir o endereço IP da porta de gerenciamento do BMC"]
* link:accessing-bmc-interface-sg6000.html["Acessando a interface BMC"]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html["Configurar definições SNMP para o controlador SG6000-CN"]
* link:setting-up-email-notifications-for-alerts.html["Configurar notificações por e-mail para alertas"]

