---
permalink: sg6000/configuring-storagegrid-connections.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up 
summary: 'Antes de implantar um dispositivo StorageGRID como nó de armazenamento em um sistema StorageGRID, você deve configurar as conexões entre o dispositivo e as redes que você planeja usar. Você pode configurar a rede navegando até o Instalador de dispositivos StorageGRID, que é pré-instalado no controlador SG6000-CN (o controlador de computação).' 
---
= Configurando conexões StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar um dispositivo StorageGRID como nó de armazenamento em um sistema StorageGRID, você deve configurar as conexões entre o dispositivo e as redes que você planeja usar. Você pode configurar a rede navegando até o Instalador de dispositivos StorageGRID, que é pré-instalado no controlador SG6000-CN (o controlador de computação).

.Passos
* link:accessing-storagegrid-appliance-installer-sg6000.html["Acessando o instalador do StorageGRID Appliance"]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verificando e atualizando a versão do Instalador de dispositivos StorageGRID"]
* link:configuring-network-links-sg6000.html["Configurando links de rede (SG6000)"]
* link:configuring-storagegrid-ip-addresses-sg6000.html["Configurando endereços IP do StorageGRID"]
* link:verifying-network-connections.html["Verificando conexões de rede"]
* link:verifying-port-level-network-connections.html["Verificando conexões de rede no nível da porta"]

