---
permalink: sg6000/reviewing-appliance-network-connections-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, network connections, network connection, network, connection, grid, admin, client, bmc, management, SANtricity System Manager, SANtricity 
summary: Antes de instalar o dispositivo StorageGRID, você deve entender quais redes podem ser conetadas ao dispositivo. 
---
= Rever as ligações de rede do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o dispositivo StorageGRID, você deve entender quais redes podem ser conetadas ao dispositivo.

Ao implantar um dispositivo StorageGRID como nó de storage em um sistema StorageGRID, você pode conectá-lo às seguintes redes:

* *Rede de grade para StorageGRID*: A rede de grade é usada para todo o tráfego interno de StorageGRID. Ele fornece conetividade entre todos os nós na grade, em todos os sites e sub-redes. A rede de Grade é necessária.
* *Rede de administração para StorageGRID*: A rede de administração é uma rede fechada usada para administração e manutenção do sistema. A rede Admin é normalmente uma rede privada e não precisa ser roteável entre sites. A rede de administração é opcional.
* *Rede de clientes para StorageGRID:* a rede de clientes é uma rede aberta usada para fornecer acesso a aplicativos clientes, incluindo S3 e Swift. A rede do cliente fornece acesso ao protocolo do cliente à grade, de modo que a rede da grade possa ser isolada e protegida. A rede do cliente é opcional.
* *Rede de gerenciamento para o Gerenciador de sistema SANtricity*: Essa rede fornece acesso ao Gerenciador de sistema SANtricity no controlador de armazenamento, permitindo que você monitore e gerencie os componentes de hardware no compartimento do controlador de armazenamento. Essa rede de gerenciamento pode ser a mesma rede de administração para StorageGRID ou pode ser uma rede de gerenciamento independente.
* *Rede de gerenciamento BMC para o controlador SG6000-CN:* esta rede fornece acesso ao controlador de gerenciamento de placa base no SG6000-CN, permitindo que você monitore e gerencie os componentes de hardware no controlador SG6000-CN. Essa rede de gerenciamento pode ser a mesma rede de administração para StorageGRID ou pode ser uma rede de gerenciamento independente.



NOTE: Para obter informações detalhadas sobre redes StorageGRID, consulte _Primer_.

.Informações relacionadas
link:gathering-installation-information-sg6000.html["Recolha de informações de instalação (SG6000)"]

link:cabling-appliance-sg6000.html["Cabeamento do aparelho (SG6000)"]

link:port-bond-modes-for-sg6000-cn-controller.html["Modos de ligação de porta para o controlador SG6000-CN"]

link:../network/index.html["Diretrizes de rede"]
