---
permalink: sg100-1000/preparing-for-installation-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, install, installation, preparation, get ready, prepare 
summary: Preparar a instalação de um dispositivo StorageGRID implica preparar o local e obter todo o hardware, cabos e ferramentas necessários. Você também deve coletar endereços IP e informações de rede. 
---
= Preparando-se para a instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Preparar a instalação de um dispositivo StorageGRID implica preparar o local e obter todo o hardware, cabos e ferramentas necessários. Você também deve coletar endereços IP e informações de rede.

.Passos
* link:preparing-site-sg100-and-sg1000.html["Preparação do local (SG100 e SG1000)"]
* link:unpacking-boxes-sg100-and-sg1000.html["Desembalar as caixas (SG100 e SG1000)"]
* link:obtaining-additional-equipment-and-tools-sg100-and-sg1000.html["Obtenção de equipamentos e ferramentas adicionais (SG100 e SG1000)"]
* link:web-browser-requirements.html["Requisitos do navegador da Web"]
* link:reviewing-appliance-network-connections-sg100-and-sg1000.html["Rever as ligações de rede do dispositivo"]
* link:gathering-installation-information-sg100-and-sg1000.html["Recolha de informações de instalação (SG100 e SG1000)"]

