---
permalink: sg100-1000/reviewing-appliance-network-connections-sg100-and-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, network connections, network connection, network, connection, grid, admin, client, bmc, management 
summary: Antes de instalar o dispositivo StorageGRID, você deve entender quais redes podem ser conetadas ao dispositivo. 
---
= Rever as ligações de rede do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o dispositivo StorageGRID, você deve entender quais redes podem ser conetadas ao dispositivo.

Ao implantar um dispositivo StorageGRID como nó em um sistema StorageGRID, você pode conectá-lo às seguintes redes:

* *Rede de grade para StorageGRID*: A rede de grade é usada para todo o tráfego interno de StorageGRID. Ele fornece conetividade entre todos os nós na grade, em todos os sites e sub-redes. A rede de Grade é necessária.
* *Rede de administração para StorageGRID*: A rede de administração é uma rede fechada usada para administração e manutenção do sistema. A rede Admin é normalmente uma rede privada e não precisa ser roteável entre sites. A rede de administração é opcional.
* *Rede de clientes para StorageGRID:* a rede de clientes é uma rede aberta usada para fornecer acesso a aplicativos clientes, incluindo S3 e Swift. A rede do cliente fornece acesso ao protocolo do cliente à grade, de modo que a rede da grade possa ser isolada e protegida. Você pode configurar a rede do cliente para que o dispositivo possa ser acessado por essa rede usando apenas as portas que você escolher abrir. A rede do cliente é opcional.
* *Rede de gerenciamento BMC para o utilitário de serviços:* esta rede fornece acesso ao controlador de gerenciamento de placa base nos SG100 e SG1000, dispositivos que permitem monitorar e gerenciar os componentes de hardware no dispositivo. Essa rede de gerenciamento pode ser a mesma rede de administração para StorageGRID ou pode ser uma rede de gerenciamento independente.


.Informações relacionadas
link:gathering-installation-information-sg100-and-sg1000.html["Recolha de informações de instalação (SG100 e SG1000)"]

link:cabling-appliance-sg100-and-sg1000.html["Cabeamento do dispositivo SG100 e SG1000)"]

link:../network/index.html["Diretrizes de rede"]

link:../primer/index.html["Primário de grelha"]
