---
permalink: sg100-1000/verifying-and-upgrading-storagegrid-appliance-installer-version.html 
sidebar: sidebar 
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, Verifying, verify, upgrading, upgrade, update, updating, Appliance Installer, version, release 
summary: A versão do Instalador de dispositivos StorageGRID no dispositivo deve corresponder à versão de software instalada no sistema StorageGRID para garantir que todos os recursos do StorageGRID sejam suportados. 
---
= Verificando e atualizando a versão do Instalador de dispositivos StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A versão do Instalador de dispositivos StorageGRID no dispositivo deve corresponder à versão de software instalada no sistema StorageGRID para garantir que todos os recursos do StorageGRID sejam suportados.

.O que você vai precisar
Você acessou o Instalador de dispositivos StorageGRID.

.Sobre esta tarefa
Os dispositivos StorageGRID vêm da fábrica pré-instalados com o Instalador de dispositivos StorageGRID. Se você estiver adicionando um dispositivo a um sistema StorageGRID atualizado recentemente, talvez seja necessário atualizar manualmente o Instalador de dispositivos StorageGRID antes de instalar o dispositivo como um novo nó.

O Instalador de dispositivos StorageGRID é atualizado automaticamente quando você atualiza para uma nova versão do StorageGRID. Não é necessário atualizar o Instalador de dispositivos StorageGRID nos nós de dispositivos instalados. Este procedimento só é necessário quando estiver a instalar um dispositivo que contenha uma versão anterior do Instalador de dispositivos StorageGRID.

.Passos
. No Instalador de dispositivos StorageGRID, selecione *Avançado* *Atualização de firmware*.
. Compare a versão atual do firmware com a versão de software instalada no seu sistema StorageGRID (no Gerenciador de Grade, selecione *Ajuda* *sobre*).
+
O segundo dígito nas duas versões deve corresponder. Por exemplo, se o seu sistema StorageGRID estiver executando a versão 11.*5*._x_._y_, a versão do Instalador de dispositivos StorageGRID deve ser 3.*5*._z_.

. Se o aparelho tiver uma versão de nível inferior do instalador do dispositivo StorageGRID, vá para a página de downloads do NetApp para StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^]

+
Inicie sessão com o nome de utilizador e a palavra-passe da sua conta NetApp.

. Baixe a versão apropriada do arquivo *suporte para dispositivos StorageGRID* e o arquivo de checksum correspondente.
+
O arquivo de suporte para dispositivos StorageGRID é um `.zip` arquivo que contém as versões de firmware atuais e anteriores para todos os modelos de dispositivos StorageGRID, em subdiretórios para cada tipo de controlador.

+
Depois de baixar o arquivo de suporte para o arquivo de dispositivos StorageGRID, extraia o `.zip` arquivo e consulte o arquivo README para obter informações importantes sobre a instalação do Instalador de dispositivos StorageGRID.

. Siga as instruções na página Atualizar firmware do Instalador de dispositivos StorageGRID para executar estas etapas:
+
.. Carregue o ficheiro de suporte apropriado (imagem de firmware) para o seu tipo de controlador e o ficheiro de checksum.
.. Atualize a partição inativa.
.. Reinicie e troque partições.
.. Atualize a segunda partição.




.Informações relacionadas
link:accessing-storagegrid-appliance-installer-sg100-and-sg1000.html["Acessando o instalador do StorageGRID Appliance"]
