---
permalink: ubuntu/planning-and-preparation.html 
sidebar: sidebar 
keywords:  
summary: Antes de implantar nós de grade e configurar a grade StorageGRID, você deve estar familiarizado com as etapas e requisitos para concluir o procedimento. 
---
= Planejamento e preparação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar nós de grade e configurar a grade StorageGRID, você deve estar familiarizado com as etapas e requisitos para concluir o procedimento.

Os procedimentos de implantação e configuração do StorageGRID presumem que você está familiarizado com a arquitetura e o funcionamento do sistema StorageGRID.

Você pode implantar um único local ou vários locais de uma só vez. No entanto, todos os locais precisam atender ao requisito mínimo de ter pelo menos três nós de storage.

Antes de iniciar uma instalação do StorageGRID, você deve:

* Entenda os requisitos de computação do StorageGRID, incluindo os requisitos mínimos de CPU e RAM para cada nó.
* Entenda como o StorageGRID oferece suporte a várias redes para separação de tráfego, segurança e conveniência administrativa e tenha um plano para quais redes você pretende anexar a cada nó do StorageGRID.
+
Consulte as diretrizes de rede do StorageGRID.

* Compreender os requisitos de storage e desempenho de cada tipo de nó de grade.
* Identifique um conjunto de servidores (físicos, virtuais ou ambos) que, no agregado, fornecem recursos suficientes para suportar o número e o tipo de nós do StorageGRID que você planeja implantar.
* Entenda os requisitos para migração de nós, se você quiser realizar manutenção programada em hosts físicos sem qualquer interrupção do serviço.
* Reúna todas as informações de rede com antecedência. A menos que você esteja usando DHCP, reúna os endereços IP para atribuir a cada nó de grade e os endereços IP dos servidores DNS (Domain Name System) e NTP (Network Time Protocol) que serão usados.
* Instale, conete e configure todo o hardware necessário, incluindo quaisquer dispositivos StorageGRID, de acordo com as especificações.
+

NOTE: As instruções de instalação e integração específicas de hardware não estão incluídas no procedimento de instalação do StorageGRID. Para saber como instalar dispositivos StorageGRID, consulte as instruções de instalação e manutenção do seu aparelho.

* Decida qual das ferramentas de implantação e configuração disponíveis você deseja usar.


.Informações relacionadas
link:../network/index.html["Diretrizes de rede"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100  SG1000"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]

link:node-container-migration-requirements.html["Requisitos de migração de contêiner de nós"]
