---
permalink: network/host-network-configuration-for-docker-deployments.html 
sidebar: sidebar 
keywords:  
summary: Antes de iniciar a implantação do StorageGRID em uma plataforma de contentor Docker, determine quais redes cada nó usará. Você deve garantir que a interface de rede de cada nó esteja configurada na interface de host física ou virtual correta e que cada rede tenha largura de banda suficiente. 
---
= Configuração de rede de host para implantações do Docker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a implantação do StorageGRID em uma plataforma de contentor Docker, determine quais redes (grade, administrador, cliente) cada nó usará. Você deve garantir que a interface de rede de cada nó esteja configurada na interface de host física ou virtual correta e que cada rede tenha largura de banda suficiente.



== Hosts físicos

Se você estiver usando hosts físicos para oferecer suporte a nós de grade:

* Certifique-se de que todos os hosts usem a mesma interface de host para cada interface de nó. Essa estratégia simplifica a configuração de host e permite a migração futura de nós.
* Obtenha um endereço IP para o próprio host físico.
+

NOTE: Uma interface física no host pode ser usada pelo próprio host e por um ou mais nós executados no host. Todos os endereços IP atribuídos ao host ou nós que usam essa interface devem ser exclusivos. O host e o nó não podem compartilhar endereços IP.

* Abra as portas necessárias para o host.




== Recomendações mínimas de largura de banda

A tabela a seguir fornece as recomendações de largura de banda mínima para cada tipo de nó StorageGRID e cada tipo de rede. Você precisa provisionar cada host físico ou virtual com largura de banda suficiente para atender aos requisitos mínimos de largura de banda agregada para o número total e tipo de nós de StorageGRID que você planeja executar nesse host.

|===
| Tipo de nó 3+| Tipo de rede 


 a| 
| Grelha | Administrador | Cliente 


 a| 
Administrador
| 10 Gbps | 1 Gbps | 1 Gbps 


 a| 
Gateway
| 10 Gbps | 1 Gbps | 10 Gbps 


 a| 
Armazenamento
| 10 Gbps | 1 Gbps | 10 Gbps 


 a| 
Arquivar
| 10 Gbps | 1 Gbps | 10 Gbps 
|===

NOTE: Esta tabela não inclui largura de banda SAN, que é necessária para acesso ao armazenamento compartilhado. Se você estiver usando storage compartilhado acessado por Ethernet (iSCSI ou FCoE), você deverá provisionar interfaces físicas separadas em cada host para fornecer largura de banda suficiente para SAN. Para evitar a introdução de um gargalo, a largura de banda da SAN para um determinado host deve corresponder aproximadamente à largura de banda da rede do nó de storage agregado para todos os nós de storage executados nesse host.

Use a tabela para determinar o número mínimo de interfaces de rede a provisionar em cada host, com base no número e no tipo de nós de StorageGRID que você planeja executar nesse host.

Por exemplo, para executar um nó de administrador, um nó de gateway e um nó de storage em um único host:

* Conetar as redes de Grade e Admin no nó Admin (requer 10 mais de 1 11 Gbps)
* Conetar as redes Grid e Client no Gateway Node (requer 10 e 10, ou 20 Gbps)
* Ligar a rede de grelha no nó de armazenamento (requer 10 Gbps)


Nesse cenário, você deve fornecer um mínimo de 11 41 Gbps e 20 Gbps ou 10 Gbps de largura de banda de rede, que pode ser atendida por duas interfaces de 40 Gbps ou cinco interfaces de 10 Gbps, potencialmente agregadas em troncos e, em seguida, compartilhadas pelas três ou mais VLANs que transportam as sub-redes Grid, Admin e Client locais para o data center físico que contém o host.

Para obter algumas maneiras recomendadas de configurar recursos físicos e de rede nos hosts do cluster StorageGRID para se preparar para a implantação do StorageGRID, consulte as informações sobre como configurar a rede host nas instruções de instalação da sua plataforma Linux.

.Informações relacionadas
link:../rhel/index.html["Instale o Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Instale Ubuntu ou Debian"]
