---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: Se você planeja usar os serviços da plataforma StorageGRID ou os pools de armazenamento em nuvem, configure redes de grade e firewalls para garantir que os pontos de extremidade de destino possam ser alcançados. Os serviços de plataforma incluem serviços externos que fornecem integração de pesquisa, notificação de eventos e replicação do CloudMirror. 
---
= Rede e portas para serviços de plataforma e Cloud Storage Pools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você planeja usar os serviços da plataforma StorageGRID ou os pools de armazenamento em nuvem, configure redes de grade e firewalls para garantir que os pontos de extremidade de destino possam ser alcançados. Os serviços de plataforma incluem serviços externos que fornecem integração de pesquisa, notificação de eventos e replicação do CloudMirror.

Os serviços de plataforma exigem acesso de nós de storage que hospedam o serviço StorageGRID ADC aos pontos de extremidade de serviço externos. Exemplos para fornecer acesso incluem:

* Nos nós de armazenamento com serviços ADC, configure redes de administração exclusivas com entradas AESL que roteam para os endpoints de destino.
* Confie na rota padrão fornecida por uma rede de clientes. Neste exemplo, o recurso rede cliente não confiável pode ser usado para restringir conexões de entrada.


Os Cloud Storage Pools também exigem acesso dos nós de storage aos pontos de extremidade fornecidos pelo serviço externo usado, como o storage Amazon S3 Glacier ou Microsoft Azure Blob.

Por padrão, os serviços de plataforma e as comunicações do Cloud Storage Pool usam as seguintes portas:

* *80*: Para URIs de endpoint que começam com `http`
* *443*: Para URIs de endpoint que começam com `https`


Uma porta diferente pode ser especificada quando o endpoint é criado ou editado.

Se você usar um servidor proxy não transparente, também deverá configurar as configurações de proxy para permitir que as mensagens sejam enviadas para endpoints externos, como um endpoint na Internet. Consulte administrar StorageGRID para saber como configurar as configurações de proxy.

Para obter mais informações sobre redes de clientes não confiáveis, consulte as instruções para administrar o StorageGRID. Para obter mais informações sobre serviços de plataforma, consulte as instruções para usar contas de locatário. Para obter mais informações sobre Cloud Storage Pools, consulte as instruções para gerenciar objetos com gerenciamento do ciclo de vida das informações.

.Informações relacionadas
link:network-port-reference.html["Referência da porta de rede"]

link:../primer/index.html["Primário de grelha"]

link:../admin/index.html["Administrar o StorageGRID"]

link:../tenant/index.html["Use uma conta de locatário"]

link:../ilm/index.html["Gerenciar objetos com ILM"]
