---
permalink: network/networking-requirements-and-guidelines.html 
sidebar: sidebar 
keywords: storagegrid, networking requirements, network requirements, nat 
summary: Você deve verificar se a infraestrutura e a configuração de rede atuais podem suportar o design de rede StorageGRID planejado. 
---
= Requisitos de rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve verificar se a infraestrutura e a configuração de rede atuais podem suportar o design de rede StorageGRID planejado.



== Requisitos gerais de rede

Todas as implantações do StorageGRID devem ser capazes de suportar as seguintes conexões.

Essas conexões podem ocorrer através das redes Grid, Admin ou Client, ou as combinações dessas redes, conforme ilustrado nos exemplos de topologia de rede.

* * Conexões de gerenciamento*: Conexões de entrada de um administrador para o nó, geralmente através de SSH. Acesso do navegador da Web ao Gerenciador de Grade, ao Gerenciador do Locatário e ao Instalador de dispositivos StorageGRID.
* * Conexões de servidor NTP*: Conexão UDP de saída que recebe uma resposta UDP de entrada.
+
Pelo menos um servidor NTP deve estar acessível pelo nó de administração principal.

* * Conexões de servidor DNS*: Conexão UDP de saída que recebe uma resposta UDP de entrada.
* * Conexões de servidor LDAP/ative Directory*: Conexão TCP de saída do serviço identidade nos nós de armazenamento.
* *AutoSupport*: Conexão TCP de saída dos nós de administração para eithersupport.NetApp.com ou um proxy configurado pelo cliente.
* *Servidor de gerenciamento de chaves externo*: Conexão TCP de saída de cada nó de dispositivo com criptografia de nó ativada.
* Conexões TCP de entrada de clientes S3 e Swift.
* Solicitações de saída de serviços da plataforma StorageGRID, como a replicação do Cloud Mirror ou de pools de storage de nuvem.


Se o StorageGRID não conseguir entrar em Contato com qualquer um dos servidores NTP ou DNS provisionados usando as regras de roteamento padrão, ele tentará automaticamente o Contato em todas as redes (Grade, Admin e Cliente), desde que os endereços IP dos servidores DNS e NTP sejam especificados. Se os servidores NTP ou DNS puderem ser alcançados em qualquer rede, o StorageGRID criará automaticamente regras de roteamento adicionais para garantir que a rede seja usada para todas as tentativas futuras de se conetar a ela.


IMPORTANT: Embora você possa usar essas rotas de host descobertas automaticamente, em geral, você deve configurar manualmente as rotas DNS e NTP para garantir a conetividade no caso de falha de descoberta automática.

Se você não estiver pronto para configurar as redes Admin e Client opcionais durante a implantação, você poderá configurar essas redes quando aprovar nós de grade durante as etapas de configuração. Além disso, você pode configurar essas redes após a conclusão da instalação usando a ferramenta Change IP, conforme descrito nas instruções de recuperação e manutenção.



== Conexões para nós de administração e nós de gateway

Os nós de administração devem sempre ser protegidos de clientes não confiáveis, como aqueles na Internet aberta. Você deve garantir que nenhum cliente não confiável possa acessar qualquer nó Admin na rede de Grade, na rede Admin ou na rede Cliente.

Os nós de administração e os nós de gateway que você pretende adicionar aos grupos de alta disponibilidade devem ser configurados com um endereço IP estático. Consulte as informações sobre grupos de alta disponibilidade nas instruções para administrar o StorageGRID.



== Usando a tradução de endereços de rede (NAT)

Não use a tradução de endereço de rede (NAT) na rede de Grade entre nós de grade ou entre sites StorageGRID. Quando você usa endereços IPv4 privados para a rede de Grade, esses endereços devem ser roteáveis diretamente de cada nó de grade em cada local. No entanto, conforme necessário, você pode usar NAT entre clientes externos e nós de grade, como fornecer um endereço IP público para um nó de gateway. O uso de NAT para fazer a ponte de um segmento de rede pública é suportado apenas quando você emprega um aplicativo de encapsulamento transparente para todos os nós da grade, o que significa que os nós da grade não exigem conhecimento de endereços IP públicos.

.Informações relacionadas
link:../primer/index.html["Primário de grelha"]

link:../admin/index.html["Administrar o StorageGRID"]

link:../maintain/index.html["Manter  recuperar"]
