---
permalink: network/post-installation-guidelines.html 
sidebar: sidebar 
keywords:  
summary: Depois de concluir a implantação e a configuração do nó de grade, siga estas diretrizes para endereçamento DHCP e alterações na configuração da rede. 
---
= Diretrizes de pós-instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de concluir a implantação e a configuração do nó de grade, siga estas diretrizes para endereçamento DHCP e alterações na configuração da rede.

* Se o DHCP foi usado para atribuir endereços IP, configure uma reserva DHCP para cada endereço IP nas redes que estão sendo usadas.
+
Só pode configurar o DHCP durante a fase de implementação. Não é possível configurar o DHCP durante a configuração.

+

IMPORTANT: Os nós reiniciam quando seus endereços IP são alterados, o que pode causar interrupções se uma alteração de endereço DHCP afetar vários nós ao mesmo tempo.

* Você deve usar os procedimentos alterar IP se quiser alterar endereços IP, máscaras de sub-rede e gateways padrão para um nó de grade. Consulte as informações sobre como configurar endereços IP nas instruções de recuperação e manutenção.
* Se você fizer alterações na configuração de rede, incluindo alterações de roteamento e gateway, a conetividade do cliente para o nó de administração principal e outros nós de grade pode ser perdida. Dependendo das alterações de rede aplicadas, talvez seja necessário restabelecer essas conexões.


.Informações relacionadas
link:../rhel/index.html["Instale o Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Instale Ubuntu ou Debian"]

link:../vmware/index.html["Instale o VMware"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100  SG1000"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]

link:../maintain/index.html["Manter  recuperar"]
