---
permalink: network/storagegrid-networking-overview.html 
sidebar: sidebar 
keywords: storagegrid, network, networking, ethernet, subnet, routing 
summary: A configuração da rede para um sistema StorageGRID requer um alto nível de experiência com comutação Ethernet, rede TCP/IP, sub-redes, roteamento de rede e firewalls. 
---
= Visão geral da rede StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A configuração da rede para um sistema StorageGRID requer um alto nível de experiência com comutação Ethernet, rede TCP/IP, sub-redes, roteamento de rede e firewalls.

Antes de configurar a rede, familiarize-se com a arquitetura StorageGRID conforme descrito no _cartilha_ de grade.

Antes de implantar e configurar o StorageGRID, você deve configurar a infraestrutura de rede. A comunicação precisa ocorrer entre todos os nós na grade e entre a grade e clientes e serviços externos.

Clientes externos e serviços externos precisam se conetar a redes StorageGRID para executar funções como as seguintes:

* Armazenar e recuperar dados de objeto
* Receber notificações por e-mail
* Acesse a interface de gerenciamento do StorageGRID (Gerenciador de grade e Gerenciador de locatário)
* Acessar o compartilhamento de auditoria (opcional)
* Fornecer serviços como:
+
** Protocolo de tempo de rede (NTP)
** Sistema de nomes de domínio (DNS)
** Servidor de gerenciamento de chaves (KMS)




A rede StorageGRID deve ser configurada adequadamente para lidar com o tráfego dessas funções e muito mais.

Depois de determinar qual das três redes StorageGRID você deseja usar e como essas redes serão configuradas, você poderá instalar e configurar os nós StorageGRID seguindo as instruções apropriadas.

.Informações relacionadas
link:../primer/index.html["Primário de grelha"]

link:../admin/index.html["Administrar o StorageGRID"]

link:../release-notes/index.html["Notas de lançamento"]

link:../rhel/index.html["Instale o Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Instale Ubuntu ou Debian"]

link:../vmware/index.html["Instale o VMware"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100  SG1000"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]
