---
permalink: sg5600/configuring-hardware.html 
sidebar: sidebar 
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Depois de aplicar energia ao dispositivo, você deve configurar o SANtricity Storage Manager, que é o software que você usará para monitorar o hardware. Você também deve configurar as conexões de rede que serão usadas pelo StorageGRID. 
---
= Configurar o hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de aplicar energia ao dispositivo, você deve configurar o SANtricity Storage Manager, que é o software que você usará para monitorar o hardware. Você também deve configurar as conexões de rede que serão usadas pelo StorageGRID.

.Passos
* link:configuring-storagegrid-connections.html["Configurando conexões StorageGRID"]
* link:configuring-santricity-storage-manager.html["Configurando o SANtricity Storage Manager"]
* link:optional-enabling-node-encryption.html["Opcional: Habilitando a criptografia de nó"]
* link:optional-changing-to-raid6-mode-sg5660-only.html["Opcional: Mudar para o modo RAID6 (apenas SG5660)"]
* link:optional-remapping-network-ports-for-appliance-sg5600-and-sg5700.html["Opcional: Remapeamento de portas de rede para o dispositivo"]

