---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, vmware, download installation files, downloading installation files 
summary: Você deve baixar os arquivos de instalação do StorageGRID e extrair os arquivos. 
---
= Transferir e extrair os ficheiros de instalação do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar os arquivos de instalação do StorageGRID e extrair os arquivos.

.Passos
. Vá para a página de downloads do NetApp para StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^]

. Selecione o botão para baixar a versão mais recente ou selecione outra versão no menu suspenso e selecione *Go*.
. Inicie sessão com o nome de utilizador e a palavra-passe da sua conta NetApp.
. Se aparecer uma instrução Caution/MustRead, leia-a e marque a caixa de seleção.
+
Você deve aplicar os hotfixes necessários depois de instalar a versão do StorageGRID. Para obter mais informações, consulte o procedimento de correção nas instruções de recuperação e manutenção.

. Leia o Contrato de Licença de Usuário final, marque a caixa de seleção e selecione *aceitar e continuar*.
. Na coluna *Instalar StorageGRID*, selecione o software apropriado.
+
Transfira o `.tgz` ficheiro de arquivo ou `.zip` para a sua plataforma.

+
** `StorageGRID-Webscale-version-VMware-uniqueID.zip`
** `StorageGRID-Webscale-version-VMware-uniqueID.tgz`





NOTE: Use o `.zip` arquivo se você estiver executando o Windows no laptop de serviço.

. Salve e extraia o arquivo de arquivo.
. Escolha os arquivos que você precisa na lista a seguir.
+
Os arquivos de que você precisa dependem da topologia de grade planejada e de como implantar o sistema StorageGRID.




NOTE: Os caminhos listados na tabela são relativos ao diretório de nível superior instalado pelo arquivo de instalação extraído.

[cols="1a,1a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./vSphere/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./vSphere/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./vsphere/NetApp-SG-version-SHA.vmdk  a| 
O arquivo de disco da máquina virtual que é usado como um modelo para criar máquinas virtuais de nó de grade.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
O arquivo de modelo Open Virtualization Format (`.ovf`) e o arquivo de manifesto (`.mf`) para implantar o nó de administração principal.



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de administração não primários.



| ./vsphere/vsphere-archive.ovf ./vsphere/vsphere-archive.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de arquivamento.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós do Gateway.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
O arquivo de (`.ovf`modelo ) e o arquivo de manifesto (`.mf`) para implantar nós de storage baseados em máquina virtual.



| Ferramenta de script de implantação | Descrição 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
Um script de shell Bash usado para automatizar a implantação de nós de grade virtual.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
Um arquivo de configuração de exemplo para uso com o `deploy-vsphere-ovftool.sh` script.



| ./vsphere/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./vsphere/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./vsphere/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado.



| ./vsphere/configure-StorageGRID.sample.json  a| 
Um arquivo de configuração de exemplo para uso com o `configure-storagegrid.py` script.



| ./vsphere/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.

|===
.Informações relacionadas
link:../maintain/index.html["Manter  recuperar"]
