---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords:  
summary: Antes de implantar nós de grade e configurar a grade StorageGRID, você deve estar familiarizado com as etapas e requisitos para concluir o procedimento. 
---
= Planejamento e preparação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implantar nós de grade e configurar a grade StorageGRID, você deve estar familiarizado com as etapas e requisitos para concluir o procedimento.

Os procedimentos de implantação e configuração do StorageGRID presumem que você está familiarizado com a arquitetura e a funcionalidade operacional do sistema StorageGRID.

Você pode implantar um único local ou vários locais de uma só vez. No entanto, todos os locais precisam atender ao requisito mínimo de ter pelo menos três nós de storage.

Antes de iniciar o procedimento de implantação do nó e configuração da grade, você deve:

* Planeje a implantação do StorageGRID.
* Instale, conete e configure todo o hardware necessário, incluindo quaisquer dispositivos StorageGRID, de acordo com as especificações.
+

NOTE: As instruções de instalação e integração específicas de hardware não estão incluídas no procedimento de instalação do StorageGRID. Para saber como instalar dispositivos StorageGRID, consulte as instruções de instalação e manutenção do seu aparelho.

* Entenda as opções de rede disponíveis e como cada opção de rede deve ser implementada em nós de grade. Consulte as diretrizes de rede do StorageGRID.
* Reúna todas as informações de rede com antecedência. A menos que você esteja usando DHCP, reúna os endereços IP para atribuir a cada nó de grade e os endereços IP dos servidores DNS (Domain Name System) e NTP (Network Time Protocol) que serão usados.
* Decida qual das ferramentas de implantação e configuração disponíveis você deseja usar.


.Informações relacionadas
link:../network/index.html["Diretrizes de rede"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100  SG1000"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]
