---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords:  
summary: Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários. 
---
= Materiais necessários
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários.

[cols="1a,2a"]
|===
| Item | Notas 


 a| 
Licença NetApp StorageGRID
 a| 
Você deve ter uma licença NetApp válida e assinada digitalmente.

*Nota*: O arquivo de instalação do StorageGRID inclui uma licença gratuita que não fornece qualquer direito de suporte para o produto.



 a| 
Arquivo de instalação do StorageGRID para VMware
 a| 
Você deve baixar o arquivo de instalação do StorageGRID e extrair os arquivos.



 a| 
Software e documentação da VMware
 a| 
Durante a instalação, você implanta nós de grade virtual em máquinas virtuais no VMware vSphere Web Client.para versões com suporte, consulte a Matriz de interoperabilidade.



 a| 
Serviço de laptop
 a| 
O sistema StorageGRID é instalado através de um laptoO portátil de serviço tem de ter:

* Porta de rede
* Cliente SSH (por exemplo, PuTTY)
* Navegador da Web suportado




 a| 
Documentação do StorageGRID
 a| 
* Notas de versão
* Instruções para administrar o StorageGRID


|===
.Informações relacionadas
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]

link:downloading-and-extracting-storagegrid-installation-files.html["Transferir e extrair os ficheiros de instalação do StorageGRID"]

link:web-browser-requirements.html["Requisitos do navegador da Web"]

link:../admin/index.html["Administrar o StorageGRID"]

link:../release-notes/index.html["Notas de lançamento"]
