---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: storagegrid, vmware, troubleshoot installation, troubleshooting installation 
summary: Se ocorrerem problemas durante a instalação do sistema StorageGRID, pode aceder aos ficheiros de registo de instalação. 
---
= Solução de problemas de instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se ocorrerem problemas durante a instalação do sistema StorageGRID, pode aceder aos ficheiros de registo de instalação.

A seguir estão os principais arquivos de log de instalação, que suporte técnico pode precisar para resolver problemas.

* `/var/local/log/install.log` (encontrado em todos os nós da grade)
* `/var/local/log/gdu-server.log` (Encontrado no nó de administração principal)


Para saber como acessar os arquivos de log, consulte as instruções para monitoramento e solução de problemas do StorageGRID. Para obter ajuda para solucionar problemas de instalação do aparelho, consulte as instruções de instalação e manutenção dos seus aparelhos. Se precisar de ajuda adicional, entre em Contato com o suporte técnico.

.Informações relacionadas
link:../monitor/index.html["Monitorizar  Resolução de problemas"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100  SG1000"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]

https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"^]
