---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: storagegrid, redhat, rhel, download installation files, downloading installation files 
summary: Você deve baixar o arquivo de instalação do StorageGRID e extrair os arquivos necessários. 
---
= Transferir e extrair os ficheiros de instalação do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve baixar o arquivo de instalação do StorageGRID e extrair os arquivos necessários.

.Passos
. Vá para a página de downloads do NetApp para StorageGRID.
+
https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^]

. Selecione o botão para baixar a versão mais recente ou selecione outra versão no menu suspenso e selecione *Go*.
. Inicie sessão com o nome de utilizador e a palavra-passe da sua conta NetApp.
. Se aparecer uma instrução Caution/MustRead, leia-a e marque a caixa de seleção.
+
Você deve aplicar os hotfixes necessários depois de instalar a versão do StorageGRID. Para obter mais informações, consulte o procedimento de correção nas instruções de recuperação e manutenção.

. Leia o Contrato de Licença de Usuário final, marque a caixa de seleção e selecione *aceitar e continuar*.
. Na coluna *Instalar StorageGRID*, selecione o software apropriado.
+
Transfira o `.tgz` ficheiro de arquivo ou `.zip` para a sua plataforma.

+
Os arquivos compatados contêm os arquivos RPM e scripts para Red Hat Enterprise Linux ou CentOS.

+

NOTE: Use o `.zip` arquivo se você estiver executando o Windows no laptop de serviço.

. Salve e extraia o arquivo de arquivo.
. Escolha os arquivos que você precisa na lista a seguir.
+
Os arquivos de que você precisa dependem da topologia de grade planejada e de como implantar o sistema StorageGRID.

+

NOTE: Os caminhos listados na tabela são relativos ao diretório de nível superior instalado pelo arquivo de instalação extraído.



[cols="1a,2a"]
|===
| Caminho e nome do arquivo | Descrição 


| ./rpms/README  a| 
Um arquivo de texto que descreve todos os arquivos contidos no arquivo de download do StorageGRID.



| ./rpms/NLF000000.txt  a| 
Uma licença gratuita que não fornece qualquer direito de suporte para o produto.



| ./rpms/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
Pacote RPM para instalar as imagens do nó StorageGRID em seus hosts RHEL ou CentOS.



| ./rpms/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
Pacote RPM para instalar o serviço de host StorageGRID em seus hosts RHEL ou CentOS.



| Ferramenta de script de implantação | Descrição 


| ./rpms/configure-StorageGRID.py  a| 
Um script Python usado para automatizar a configuração de um sistema StorageGRID.



| ./rpms/configure-sga.py  a| 
Um script Python usado para automatizar a configuração de dispositivos StorageGRID.



| ./rpms/configure-StorageGRID.sample.json  a| 
Um arquivo de configuração de exemplo para uso com o `configure-storagegrid.py` script.



| ./rpms/StorageGRID-ssoauth.py  a| 
Um exemplo de script Python que você pode usar para fazer login na API de Gerenciamento de Grade quando o logon único estiver ativado.



| ./rpms/configure-StorageGRID.blank.json  a| 
Um arquivo de configuração em branco para uso com o `configure-storagegrid.py` script.



| ./rpms/extras/ansible  a| 
Exemplo de função do Ansible e manual de estratégia para configurar hosts RHEL ou CentOS para implantação de contêineres do StorageGRID. Você pode personalizar a função ou o manual de estratégia conforme necessário.

|===
.Informações relacionadas
link:../maintain/index.html["Manter  recuperar"]
