---
permalink: rhel/installation-overview.html 
sidebar: sidebar 
keywords: storagegrid, rhel installation, redhat installation, redhat linux, centos installation 
summary: A instalação de um sistema StorageGRID em um ambiente Linux Red Hat Enterprise inclui três etapas principais. 
---
= Visão geral da instalação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A instalação de um sistema StorageGRID em um ambiente Linux Red Hat Enterprise (RHEL) ou CentOS Linux inclui três etapas principais.

. *Preparação*: Durante o Planejamento e a preparação, você executa as seguintes tarefas:
+
** Saiba mais sobre os requisitos de hardware e armazenamento do StorageGRID.
** Saiba mais sobre os detalhes da rede StorageGRID para que você possa configurar sua rede adequadamente. Para obter mais informações, consulte as diretrizes de rede do StorageGRID.
** Identifique e prepare os servidores físicos ou virtuais que você planeja usar para hospedar seus nós de grade do StorageGRID.
** Nos servidores que você preparou:
+
*** Instale o Linux
*** Configure a rede host
*** Configurar o armazenamento do host
*** Instale o Docker
*** Instale os serviços de host do StorageGRID




. *Implantação*: Implante nós de grade usando a interface de usuário apropriada. Quando você implementa nós de grade, eles são criados como parte do sistema StorageGRID e conetados a uma ou mais redes.
+
.. Use os arquivos de configuração de nó e linha de comando do Linux para implantar nós de grade baseados em software nos hosts preparados na etapa 1.
.. Use o Instalador de dispositivos StorageGRID para implantar nós de dispositivos StorageGRID.
+

NOTE: As instruções de instalação e integração específicas de hardware não estão incluídas no procedimento de instalação do StorageGRID. Para saber como instalar dispositivos StorageGRID, consulte as instruções de instalação e manutenção do seu aparelho.



. *Configuração*: Quando todos os nós tiverem sido implantados, use o StorageGRIDGrid Manager para configurar a grade e concluir a instalação.


Essas instruções recomendam uma abordagem padrão para implantar e configurar um sistema StorageGRID. Consulte também as informações sobre as seguintes abordagens alternativas:

* Usar uma estrutura de orquestração padrão, como Ansible, Puppet ou Chef, para instalar o RHEL ou CentOS, configurar rede e armazenamento, instalar o Docker e o serviço de host StorageGRID e implantar nós de grade virtual.
* Automatize a implantação e configuração do sistema StorageGRID usando um script de configuração Python (fornecido no arquivo de instalação).
* Automatize a implantação e a configuração dos nós de grade do dispositivo com um script de configuração Python (disponível no arquivo de instalação ou no instalador do dispositivo StorageGRID).
* Se você é um desenvolvedor avançado de implantações do StorageGRID, use as APIS REST de instalação para automatizar a instalação de nós de grade do StorageGRID.


.Informações relacionadas
link:planning-and-preparation.html["Planejamento e preparação"]

link:deploying-virtual-grid-nodes.html["Implantando nós de grade virtual"]

link:configuring-grid-and-completing-installation.html["Configurar a grelha e concluir a instalação"]

link:automating-installation.html["Automatizando a instalação"]

link:overview-of-installation-rest-api.html["Visão geral da API REST de instalação"]

link:../network/index.html["Diretrizes de rede"]
