---
permalink: rhel/required-materials.html 
sidebar: sidebar 
keywords: storagegrid, redhat required materials, rhel required materials, redhat installation, rhel installation, storagegrid license 
summary: Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários. 
---
= Materiais necessários
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de instalar o StorageGRID, você deve reunir e preparar os materiais necessários.

[cols="1a,2a"]
|===
| Item | Notas 


 a| 
Licença NetApp StorageGRID
 a| 
Você deve ter uma licença NetApp válida e assinada digitalmente.

*Nota*: Uma licença de não produção, que pode ser usada para testes e grades de prova de conceito, está incluída no arquivo de instalação do StorageGRID.



 a| 
Arquivo de instalação do StorageGRID
 a| 
Você deve baixar o arquivo de instalação do StorageGRID e extrair os arquivos.



 a| 
Serviço de laptop
 a| 
O sistema StorageGRID é instalado através de um computador portátil de serviço.

O computador portátil de serviço deve ter:

* Porta de rede
* Cliente SSH (por exemplo, PuTTY)
* Navegador da Web suportado




 a| 
Documentação do StorageGRID
 a| 
* Notas de versão
* Instruções para administrar o StorageGRID


|===
.Informações relacionadas
link:downloading-and-extracting-storagegrid-installation-files.html["Transferir e extrair os ficheiros de instalação do StorageGRID"]

link:web-browser-requirements.html["Requisitos do navegador da Web"]

link:../admin/index.html["Administrar o StorageGRID"]

link:../release-notes/index.html["Notas de lançamento"]
