---
permalink: admin/creating-relying-party-trusts-in-ad-fs.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Criando confianças de parte confiáveis no AD FS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve usar os Serviços de Federação do ative Directory (AD FS) para criar uma confiança de parte confiável para cada nó de administração em seu sistema. Você pode criar trusts confiáveis de parte usando comandos do PowerShell, importando metadados SAML do StorageGRID ou inserindo os dados manualmente.



== Criando uma confiança de parte confiável usando o Windows PowerShell

Você pode usar o Windows PowerShell para criar rapidamente uma ou mais trusts de parte confiáveis.

.O que você vai precisar
* Você configurou o SSO no StorageGRID e sabe o nome de domínio totalmente qualificado (ou o endereço IP) e o identificador de parte confiável para cada nó de administrador no seu sistema.
+

NOTE: Você deve criar uma confiança de parte confiável para cada nó de administrador no seu sistema StorageGRID. Ter uma confiança de parte confiável para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.

* Você tem experiência em criar confiança de parte confiável no AD FS ou tem acesso à documentação do Microsoft AD FS.
* Você está usando o snap-in Gerenciamento do AD FS e pertence ao grupo Administradores.


.Sobre esta tarefa
Estas instruções aplicam-se ao AD FS 4,0, que está incluído no Windows Server 2016. Se você estiver usando o AD FS 3,0, que está incluído no Windows 2012 R2, você notará pequenas diferenças no procedimento. Consulte a documentação do Microsoft AD FS se tiver dúvidas.

.Passos
. No menu Iniciar do Windows, clique com o botão direito do Mouse no ícone do PowerShell e selecione *Executar como Administrador*.
. No prompt de comando do PowerShell, digite o seguinte comando:
+
`Add-AdfsRelyingPartyTrust -Name "_Admin_Node_Identifer_" -MetadataURL "https://_Admin_Node_FQDN_/api/saml-metadata"`

+
** Para `_Admin_Node_Identifier_`, insira o Identificador de parte dependente para o nó Admin, exatamente como aparece na página Início de sessão único. Por exemplo, `SG-DC1-ADM1`.
** Para `_Admin_Node_FQDN_`, introduza o nome de domínio totalmente qualificado para o mesmo nó de administração. (Se necessário, você pode usar o endereço IP do nó em vez disso. No entanto, se você inserir um endereço IP aqui, esteja ciente de que você deve atualizar ou recriar essa confiança de parte confiável se esse endereço IP mudar alguma vez.)


. No Gerenciador do Windows Server, selecione *Ferramentas* > *Gerenciamento do AD FS*.
+
A ferramenta de gerenciamento do AD FS é exibida.

. Selecione *AD FS* > *confiar em parts*.
+
É apresentada a lista de confianças de partes dependentes.

. Adicione uma Política de Controle de Acesso à confiança da entidade dependente recém-criada:
+
.. Localize a confiança de quem confia que você acabou de criar.
.. Clique com o botão direito do rato na fidedignidade e selecione *Editar política de controlo de acesso*.
.. Selecione uma política de controlo de acesso.
.. Clique em *Apply* e clique em *OK*


. Adicione uma Política de emissão de reclamação à recém-criada confiança da parte dependente:
+
.. Localize a confiança de quem confia que você acabou de criar.
.. Clique com o botão direito do rato na confiança e selecione *Editar política de emissão de reclamação*.
.. Clique em *Adicionar regra*.
.. Na página Selecionar modelo de regra, selecione *Enviar atributos LDAP como reivindicações* na lista e clique em *Avançar*.
.. Na página Configurar regra, insira um nome de exibição para essa regra.
+
Por exemplo, *ObjectGUID to Name ID*.

.. Para o Attribute Store, selecione *ative Directory*.
.. Na coluna LDAP Attribute da tabela Mapping, digite *objectGUID*.
.. Na coluna Outgoing Claim Type (tipo de reclamação de saída) da tabela Mapeamento, selecione *Name ID* (ID do nome) na lista suspensa.
.. Clique em *Finish* e clique em *OK*.


. Confirme se os metadados foram importados com sucesso.
+
.. Clique com o botão direito do rato na confiança da parte dependente para abrir as suas propriedades.
.. Confirme se os campos nas guias *Endpoints*, *Identificadores* e *assinatura* estão preenchidos.
+
Se os metadados estiverem ausentes, confirme se o endereço de metadados da Federação está correto ou simplesmente insira os valores manualmente.



. Repita essas etapas para configurar uma confiança de parte confiável para todos os nós de administração no sistema StorageGRID.
. Quando terminar, regresse ao StorageGRID e link:testing-relying-party-trusts.html["teste todos os trusts de confiança"]confirme que estão configurados corretamente.




== Criando uma confiança de parte confiável importando metadados de federação

Você pode importar os valores de cada confiança de parte confiável acessando os metadados SAML para cada nó de administração.

.O que você vai precisar
* Você configurou o SSO no StorageGRID e sabe o nome de domínio totalmente qualificado (ou o endereço IP) e o identificador de parte confiável para cada nó de administrador no seu sistema.
+

NOTE: Você deve criar uma confiança de parte confiável para cada nó de administrador no seu sistema StorageGRID. Ter uma confiança de parte confiável para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.

* Você tem experiência em criar confiança de parte confiável no AD FS ou tem acesso à documentação do Microsoft AD FS.
* Você está usando o snap-in Gerenciamento do AD FS e pertence ao grupo Administradores.


.Sobre esta tarefa
Estas instruções aplicam-se ao AD FS 4,0, que está incluído no Windows Server 2016. Se você estiver usando o AD FS 3,0, que está incluído no Windows 2012 R2, você notará pequenas diferenças no procedimento. Consulte a documentação do Microsoft AD FS se tiver dúvidas.

.Passos
. No Gerenciador do Windows Server, clique em *Ferramentas* e selecione *Gerenciamento do AD FS*.
. Em ações, clique em *Adicionar confiança de parte dependente*.
. Na página de boas-vindas, escolha *reconhecimento de reclamações* e clique em *Iniciar*.
. Selecione *Importar dados sobre a parte dependente publicada on-line ou em uma rede local*.
. Em *Endereço de metadados de Federação (nome do host ou URL)*, digite o local dos metadados SAML para este nó de administração:
+
`https://_Admin_Node_FQDN_/api/saml-metadata`

+
Para `_Admin_Node_FQDN_`, introduza o nome de domínio totalmente qualificado para o mesmo nó de administração. (Se necessário, você pode usar o endereço IP do nó em vez disso. No entanto, se você inserir um endereço IP aqui, esteja ciente de que você deve atualizar ou recriar essa confiança de parte confiável se esse endereço IP mudar alguma vez.)

. Conclua o assistente confiar na parte confiável, salve a confiança da parte confiável e feche o assistente.
+

NOTE: Ao inserir o nome de exibição, use o Identificador de parte confiável para o nó Admin, exatamente como ele aparece na página de logon único no Gerenciador de Grade. Por exemplo, `SG-DC1-ADM1`.

. Adicionar uma regra de reclamação:
+
.. Clique com o botão direito do rato na confiança e selecione *Editar política de emissão de reclamação*.
.. Clique em *Adicionar regra*:
.. Na página Selecionar modelo de regra, selecione *Enviar atributos LDAP como reivindicações* na lista e clique em *Avançar*.
.. Na página Configurar regra, insira um nome de exibição para essa regra.
+
Por exemplo, *ObjectGUID to Name ID*.

.. Para o Attribute Store, selecione *ative Directory*.
.. Na coluna LDAP Attribute da tabela Mapping, digite *objectGUID*.
.. Na coluna Outgoing Claim Type (tipo de reclamação de saída) da tabela Mapeamento, selecione *Name ID* (ID do nome) na lista suspensa.
.. Clique em *Finish* e clique em *OK*.


. Confirme se os metadados foram importados com sucesso.
+
.. Clique com o botão direito do rato na confiança da parte dependente para abrir as suas propriedades.
.. Confirme se os campos nas guias *Endpoints*, *Identificadores* e *assinatura* estão preenchidos.
+
Se os metadados estiverem ausentes, confirme se o endereço de metadados da Federação está correto ou simplesmente insira os valores manualmente.



. Repita essas etapas para configurar uma confiança de parte confiável para todos os nós de administração no sistema StorageGRID.
. Quando terminar, regresse ao StorageGRID e link:testing-relying-party-trusts.html["teste todos os trusts de confiança"]confirme que estão configurados corretamente.




== Criando uma confiança de parte confiável manualmente

Se você optar por não importar os dados para as partes confiáveis, você poderá inserir os valores manualmente.

.O que você vai precisar
* Você configurou o SSO no StorageGRID e sabe o nome de domínio totalmente qualificado (ou o endereço IP) e o identificador de parte confiável para cada nó de administrador no seu sistema.
+

NOTE: Você deve criar uma confiança de parte confiável para cada nó de administrador no seu sistema StorageGRID. Ter uma confiança de parte confiável para cada nó de administração garante que os usuários possam entrar e sair com segurança de qualquer nó de administração.

* Você tem o certificado personalizado que foi carregado para a interface de gerenciamento do StorageGRID ou sabe como fazer login em um nó de administrador a partir do shell de comando.
* Você tem experiência em criar confiança de parte confiável no AD FS ou tem acesso à documentação do Microsoft AD FS.
* Você está usando o snap-in Gerenciamento do AD FS e pertence ao grupo Administradores.


.Sobre esta tarefa
Estas instruções aplicam-se ao AD FS 4,0, que está incluído no Windows Server 2016. Se você estiver usando o AD FS 3,0, que está incluído no Windows 2012 R2, você notará pequenas diferenças no procedimento. Consulte a documentação do Microsoft AD FS se tiver dúvidas.

.Passos
. No Gerenciador do Windows Server, clique em *Ferramentas* e selecione *Gerenciamento do AD FS*.
. Em ações, clique em *Adicionar confiança de parte dependente*.
. Na página de boas-vindas, escolha *reconhecimento de reclamações* e clique em *Iniciar*.
. Selecione *Digite os dados sobre a parte confiável manualmente* e clique em *Avançar*.
. Conclua o assistente confiança da parte dependente:
+
.. Introduza um nome de apresentação para este nó de administração.
+
Para obter consistência, use o Identificador de parte confiável para o nó Admin, exatamente como ele aparece na página de logon único no Gerenciador de Grade. Por exemplo, `SG-DC1-ADM1`.

.. Ignore a etapa para configurar um certificado de criptografia de token opcional.
.. Na página Configurar URL, marque a caixa de seleção *Ativar suporte para o protocolo SAML 2,0 WebSSO*.
.. Digite o URL do endpoint do serviço SAML para o nó Admin:
+
`https://_Admin_Node_FQDN_/api/saml-response`

+
Para `_Admin_Node_FQDN_`, introduza o nome de domínio totalmente qualificado para o nó Admin. (Se necessário, você pode usar o endereço IP do nó em vez disso. No entanto, se você inserir um endereço IP aqui, esteja ciente de que você deve atualizar ou recriar essa confiança de parte confiável se esse endereço IP mudar alguma vez.)

.. Na página Configurar Identificadores, especifique o Identificador da parte de dependência para o mesmo nó de administração:
+
`_Admin_Node_Identifier_`

+
Para `_Admin_Node_Identifier_`, insira o Identificador de parte dependente para o nó Admin, exatamente como aparece na página Início de sessão único. Por exemplo, `SG-DC1-ADM1`.

.. Revise as configurações, salve a confiança da parte confiável e feche o assistente.
+
A caixa de diálogo Editar política de emissão de reclamação é exibida.

+

NOTE: Se a caixa de diálogo não for exibida, clique com o botão direito do Mouse no Trust e selecione *Editar política de emissão de reclamação*.



. Para iniciar o assistente de regra de reclamação, clique em *Adicionar regra*:
+
.. Na página Selecionar modelo de regra, selecione *Enviar atributos LDAP como reivindicações* na lista e clique em *Avançar*.
.. Na página Configurar regra, insira um nome de exibição para essa regra.
+
Por exemplo, *ObjectGUID to Name ID*.

.. Para o Attribute Store, selecione *ative Directory*.
.. Na coluna LDAP Attribute da tabela Mapping, digite *objectGUID*.
.. Na coluna Outgoing Claim Type (tipo de reclamação de saída) da tabela Mapeamento, selecione *Name ID* (ID do nome) na lista suspensa.
.. Clique em *Finish* e clique em *OK*.


. Clique com o botão direito do rato na confiança da parte dependente para abrir as suas propriedades.
. Na guia *Endpoints*, configure o endpoint para logout único (SLO):
+
.. Clique em *Add SAML*.
.. Selecione *Endpoint Type* > *SAML Logout*.
.. Selecione *Binding* > *Redirect*.
.. No campo *URL confiável*, insira a URL usada para logout único (SLO) deste nó Admin:
+
`https://_Admin_Node_FQDN_/api/saml-logout`

+
Para `_Admin_Node_FQDN_`, introduza o nome de domínio totalmente qualificado do nó de administração. (Se necessário, você pode usar o endereço IP do nó em vez disso. No entanto, se você inserir um endereço IP aqui, esteja ciente de que você deve atualizar ou recriar essa confiança de parte confiável se esse endereço IP mudar alguma vez.)

.. Clique em *OK*.


. Na guia *assinatura*, especifique o certificado de assinatura para essa confiança de parte confiável:
+
.. Adicione o certificado personalizado:
+
*** Se tiver o certificado de gestão personalizado que carregou no StorageGRID, selecione esse certificado.
*** Se você não tiver o certificado personalizado, faça login no Admin Node, vá para `/var/local/mgmt-api` o diretório do Admin Node e adicione o `custom-server.crt` arquivo de certificado.
+
*Observação:* usando o certificado padrão do Admin Node (`server.crt`) não é recomendado. Se o nó Admin falhar, o certificado padrão será regenerado quando você recuperar o nó e você precisará atualizar a confiança da parte confiável.



.. Clique em *Apply* e clique em *OK*.
+
As propriedades da parte dependente são salvas e fechadas.



. Repita essas etapas para configurar uma confiança de parte confiável para todos os nós de administração no sistema StorageGRID.
. Quando terminar, regresse ao StorageGRID e link:testing-relying-party-trusts.html["teste todos os trusts de confiança"]confirme que estão configurados corretamente.

