---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords:  
summary: O StorageGRID suporta até três interfaces de rede por nó de grade, permitindo que você configure a rede para cada nó de grade individual de acordo com seus requisitos de segurança e acesso. 
---
= Diretrizes para redes StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID suporta até três interfaces de rede por nó de grade, permitindo que você configure a rede para cada nó de grade individual de acordo com seus requisitos de segurança e acesso.


NOTE: Para modificar ou adicionar uma rede para um nó de grade, consulte as instruções de recuperação e manutenção. Para obter mais informações sobre a topologia de rede, consulte as instruções de rede.



== Rede de rede

Obrigatório. A rede de grade é usada para todo o tráfego interno do StorageGRID. Ele fornece conetividade entre todos os nós na grade, em todos os sites e sub-redes.



== Rede de administração

Opcional. A rede de administração é normalmente utilizada para administração e manutenção do sistema. Ele também pode ser usado para acesso ao protocolo cliente. A rede Admin é normalmente uma rede privada e não precisa ser roteável entre sites.



== Rede de clientes

Opcional. A rede de clientes é uma rede aberta normalmente usada para fornecer acesso a aplicativos clientes S3 e Swift, para que a rede de Grade possa ser isolada e protegida. A rede do cliente pode se comunicar com qualquer sub-rede acessível através do gateway local.



== Diretrizes

* Cada nó de grade do StorageGRID requer uma interface de rede dedicada, endereço IP, máscara de sub-rede e gateway para cada rede à qual está atribuído.
* Um nó de grade não pode ter mais de uma interface em uma rede.
* Um único gateway, por rede, por nó de grade é suportado e deve estar na mesma sub-rede que o nó. Você pode implementar roteamento mais complexo no gateway, se necessário.
* Em cada nó, cada rede mapeia para uma interface de rede específica.
+
[cols="1a,1a"]
|===
| Rede | Nome da interface 


 a| 
Grelha
 a| 
eth0



 a| 
Admin (opcional)
 a| 
eth1



 a| 
Cliente (opcional)
 a| 
eth2

|===
* Se o nó estiver conetado a um dispositivo StorageGRID, portas específicas serão usadas para cada rede. Para obter mais detalhes, consulte as instruções de instalação do seu aparelho.
* A rota padrão é gerada automaticamente, por nó. Se o eth2 estiver ativado, o 0,0.0.0/0 usará a rede do cliente no eth2. Se o eth2 não estiver ativado, o 0,0.0.0/0 usará a rede de Grade no eth0.
* A rede do cliente não se torna operacional até que o nó da grade se junte à grade
* A rede Admin pode ser configurada durante a implantação do nó de grade para permitir o acesso à interface do usuário de instalação antes que a grade esteja totalmente instalada.


.Informações relacionadas
link:../maintain/index.html["Manter  recuperar"]

link:../network/index.html["Diretrizes de rede"]
