---
permalink: admin/managing-full-storage-nodes.html 
sidebar: sidebar 
keywords:  
summary: 'À medida que os nós de storage atingem a capacidade, você precisa expandir o sistema StorageGRID com a adição de um novo storage. Há três opções disponíveis: Adicionar volumes de storage, adicionar compartimentos de expansão de storage e adicionar nós de storage.' 
---
= Gerenciamento de nós de storage completos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À medida que os nós de storage atingem a capacidade, você precisa expandir o sistema StorageGRID com a adição de um novo storage. Há três opções disponíveis: Adicionar volumes de storage, adicionar compartimentos de expansão de storage e adicionar nós de storage.



== Adição de volumes de armazenamento

Cada nó de storage oferece suporte a um número máximo de volumes de storage. O máximo definido varia de acordo com a plataforma. Se um nó de armazenamento contiver menos do que o número máximo de volumes de armazenamento, pode adicionar volumes para aumentar a sua capacidade. Consulte as instruções para expandir um sistema StorageGRID.



== Adição de gavetas de expansão de storage

Alguns nós de storage de dispositivos StorageGRID, como o SG6060, podem dar suporte a gavetas de storage adicionais. Se você tiver dispositivos StorageGRID com funcionalidades de expansão que ainda não foram expandidas para a capacidade máxima, poderá adicionar compartimentos de storage para aumentar a capacidade. Consulte as instruções para expandir um sistema StorageGRID.



== Adição de nós de storage

Você pode aumentar a capacidade de storage adicionando nós de storage. Deve-se ter em consideração cuidadosamente as regras de ILM e os requisitos de capacidade atualmente ativos ao adicionar armazenamento. Consulte as instruções para expandir um sistema StorageGRID.

.Informações relacionadas
link:../expand/index.html["Expanda sua grade"]
