---
permalink: admin/monitoring-data-migration.html 
sidebar: sidebar 
keywords:  
summary: A migração de dados deve ser monitorada e ajustada conforme necessário para garantir que os dados sejam colocados de acordo com a política de ILM dentro do prazo exigido. 
---
= Monitoramento da migração de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A migração de dados deve ser monitorada e ajustada conforme necessário para garantir que os dados sejam colocados de acordo com a política de ILM dentro do prazo exigido.

Esta tabela lista os atributos que você deve monitorar durante a migração de dados e os problemas que eles representam.

Se você usar políticas de classificação de tráfego com limites de taxa para reduzir a ingestão, poderá monitorar a taxa observada em conjunto com as estatísticas descritas na tabela a seguir e reduzir os limites, se necessário.

[cols="1a,2a"]
|===
| Monitorar | Descrição 


 a| 
Número de objetos aguardando avaliação ILM
 a| 
. Selecione *Support* > *Tools* > *Grid Topology*.
. Selecione *_deployment_* > *Overview* > *Main*.
. Na seção ILM Activity, monitore o número de objetos mostrados para os seguintes atributos:
+
** *Aguardando - todos (XQUZ)*: O número total de objetos aguardando avaliação ILM.
** *Aguardando - Cliente (XCQZ)*: O número total de objetos aguardando avaliação ILM das operações do cliente (por exemplo, ingest).


. Se o número de objetos mostrados para qualquer um desses atributos exceder 100.000, diminua a taxa de ingestão de objetos para reduzir a carga no sistema StorageGRID.




 a| 
Capacidade de armazenamento do sistema de arquivamento direcionado
 a| 
Se a política de ILM salvar uma cópia dos dados migrados para um sistema de armazenamento de arquivamento de destino (fita ou nuvem), monitore a capacidade do sistema de armazenamento de arquivamento de destino para garantir que haja capacidade suficiente para os dados migrados.



 a| 
*Archive Node* > *ARC* > *Store*
 a| 
Se um alarme para o atributo *Store Failures (ARVF)* for acionado, o sistema de armazenamento de arquivos alvo pode ter atingido a capacidade. Verifique o sistema de armazenamento de arquivos alvo e resolva quaisquer problemas que acionaram um alarme.

|===