---
permalink: admin/reviewing-storagegrid-encryption-methods.html 
sidebar: sidebar 
keywords:  
summary: O StorageGRID fornece várias opções para criptografar dados. Você deve analisar os métodos disponíveis para determinar quais métodos atendem aos requisitos de proteção de dados. 
---
= Rever os métodos de encriptação StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O StorageGRID fornece várias opções para criptografar dados. Você deve analisar os métodos disponíveis para determinar quais métodos atendem aos requisitos de proteção de dados.

A tabela fornece um resumo de alto nível dos métodos de criptografia disponíveis no StorageGRID.

[cols="1a,1a,1a"]
|===
| Opção de criptografia | Como funciona | Aplica-se a 


 a| 
Servidor de gerenciamento de chaves (KMS) no Grid Manager
 a| 
Configure um servidor de gerenciamento de chaves para o site StorageGRID (*Configuração* > *Configurações do sistema* > *servidor de gerenciamento de chaves*) e habilite a criptografia de nó para o dispositivo. Em seguida, um nó de dispositivo se coneta ao KMS para solicitar uma chave de criptografia de chave (KEK). Essa chave criptografa e descriptografa a chave de criptografia de dados (DEK) em cada volume.
 a| 
Nós de dispositivo que têm *Node Encryption* ativado durante a instalação. Todos os dados no dispositivo são protegidos contra perda física ou remoção do data center. Pode ser usado com alguns dispositivos de armazenamento e serviços StorageGRID.



 a| 
Conduza a segurança no Gerenciador de sistemas do SANtricity
 a| 
Se o recurso Segurança da unidade estiver habilitado para um dispositivo de armazenamento, você poderá usar o Gerenciador de sistema do SANtricity para criar e gerenciar a chave de segurança. A chave é necessária para aceder aos dados nas unidades seguras.
 a| 
Dispositivos de storage com unidades Full Disk Encryption (FDE) ou unidades FIPS (Federal Information Processing Standard). Todos os dados nas unidades protegidas são protegidos contra perda física ou remoção do data center. Não pode ser usado com alguns dispositivos de armazenamento ou com qualquer dispositivo de serviço.

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg5600/index.html["SG5600 dispositivos de armazenamento"]



 a| 
Opção de grade de criptografia de objetos armazenados
 a| 
A opção *Stored Object Encryption* pode ser ativada no Grid Manager (*Configuration* > *System Settings* > *Grid Options*). Quando ativado, todos os novos objetos que não são criptografados no nível do bucket ou no nível do objeto são criptografados durante a ingestão.
 a| 
Dados de objeto S3 e Swift recém-ingeridos.os objetos armazenados existentes não são criptografados. Os metadados de objetos e outros dados confidenciais não são criptografados.

link:configuring-stored-object-encryption.html["Configurando a criptografia de objeto armazenado"]



 a| 
Criptografia de bucket do S3
 a| 
Você emite uma solicitação de criptografia PUT Bucket para habilitar a criptografia para o bucket. Todos os novos objetos que não são criptografados no nível do objeto são criptografados durante a ingestão.
 a| 
Apenas dados de objetos S3 recém-ingeridos.a encriptação tem de ser especificada para o intervalo. Os objetos bucket existentes não são criptografados. Os metadados de objetos e outros dados confidenciais não são criptografados.

link:../s3/index.html["Use S3"]



 a| 
Criptografia do lado do servidor de objetos S3 (SSE)
 a| 
Você emite uma solicitação S3 para armazenar um objeto e incluir o `x-amz-server-side-encryption` cabeçalho da solicitação.
 a| 
Somente dados de objeto S3 recém-ingeridos.a criptografia deve ser especificada para o objeto. Os metadados de objetos e outros dados confidenciais não são criptografados.

StorageGRID gerencia as chaves.

link:../s3/index.html["Use S3"]



 a| 
Criptografia do lado do servidor de objetos S3 com chaves fornecidas pelo cliente (SSE-C)
 a| 
Você emite uma solicitação S3 para armazenar um objeto e incluir três cabeçalhos de solicitação.

* `x-amz-server-side-encryption-customer-algorithm`
* `x-amz-server-side-encryption-customer-key`
* `x-amz-server-side-encryption-customer-key-MD5`

 a| 
Somente dados de objeto S3 recém-ingeridos.a criptografia deve ser especificada para o objeto. Os metadados de objetos e outros dados confidenciais não são criptografados.

As chaves são gerenciadas fora do StorageGRID.

link:../s3/index.html["Use S3"]



 a| 
Criptografia de volume externo ou datastore
 a| 
Você usa um método de criptografia fora do StorageGRID para criptografar um volume ou armazenamento de dados inteiro, se sua plataforma de implantação o suportar.
 a| 
Todos os dados de objetos, metadados e dados de configuração do sistema, supondo que cada volume ou datastore seja criptografado.

Um método de criptografia externo fornece controle mais rigoroso sobre algoritmos e chaves de criptografia. Pode ser combinado com os outros métodos listados.



 a| 
Criptografia de objetos fora do StorageGRID
 a| 
Você usa um método de criptografia fora do StorageGRID para criptografar dados e metadados de objetos antes que eles sejam ingeridos no StorageGRID.
 a| 
Somente dados e metadados de objetos (os dados de configuração do sistema não são criptografados).

Um método de criptografia externo fornece controle mais rigoroso sobre algoritmos e chaves de criptografia. Pode ser combinado com os outros métodos listados.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html["Amazon Simple Storage Service - Guia do desenvolvedor: Protegendo dados usando criptografia do lado do cliente"^]

|===


== Usando vários métodos de criptografia

Dependendo dos seus requisitos, você pode usar mais de um método de criptografia de cada vez. Por exemplo:

* Você pode usar um KMS para proteger os nós do dispositivo e também usar o recurso de segurança da unidade no Gerenciador de sistema do SANtricity para "criptografar" os dados nas unidades de autocriptografia nos mesmos dispositivos.
* Você pode usar um KMS para proteger dados nos nós do dispositivo e também usar a opção de grade criptografia de objetos armazenados para criptografar todos os objetos quando eles são ingeridos.


Se apenas uma pequena parte de seus objetos exigir criptografia, considere controlar a criptografia no intervalo ou no nível de objeto individual. Ativar vários níveis de criptografia tem um custo de desempenho adicional.
