---
permalink: admin/updating-storagegrid-license-information.html 
sidebar: sidebar 
keywords:  
summary: Você deve atualizar as informações de licença do seu sistema StorageGRID a qualquer momento que os termos de sua licença mudarem. Por exemplo, você deve atualizar as informações da licença se adquirir capacidade de armazenamento adicional para sua grade. 
---
= Atualizando informações de licença do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve atualizar as informações de licença do seu sistema StorageGRID a qualquer momento que os termos de sua licença mudarem. Por exemplo, você deve atualizar as informações da licença se adquirir capacidade de armazenamento adicional para sua grade.

.O que você vai precisar
* Você deve ter um novo arquivo de licença para aplicar ao seu sistema StorageGRID.
* Você deve ter permissões de acesso específicas.
* Você deve ter a senha de provisionamento.


.Passos
. Selecione *Manutenção* > *sistema* > *Licença*.
. Introduza a frase-passe de aprovisionamento do seu sistema StorageGRID na caixa de texto *frase-passe de aprovisionamento*.
. Clique em *Procurar*.
. Na caixa de diálogo abrir, localize e selecione o novo arquivo de licença (`.txt`) e clique em *abrir*.
+
O novo ficheiro de licença é validado e apresentado.

. Clique em *Salvar*.

