---
permalink: s3/benefits-of-active-idle-and-concurrent-http-connections.html 
sidebar: sidebar 
keywords:  
summary: Como configurar conexões HTTP pode afetar o desempenho do sistema StorageGRID. As configurações diferem dependendo se a conexão HTTP está ativa ou inativa ou se você tem várias conexões simultâneas. 
---
= Benefícios de conexões HTTP ativas, ociosas e simultâneas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como configurar conexões HTTP pode afetar o desempenho do sistema StorageGRID. As configurações diferem dependendo se a conexão HTTP está ativa ou inativa ou se você tem várias conexões simultâneas.

Você pode identificar os benefícios de desempenho para os seguintes tipos de conexões HTTP:

* Conexões HTTP ociosas
* Conexões HTTP ativas
* Conexões HTTP simultâneas


.Informações relacionadas
* link:benefits-of-keeping-idle-http-connections-open.html["Benefícios de manter conexões HTTP ociosas abertas"]
* link:benefits-of-active-http-connections.html["Benefícios de conexões HTTP ativas"]
* link:benefits-of-concurrent-http-connections.html["Benefícios de conexões HTTP simultâneas"]
* link:separation-of-http-connection-pools-for-read-and-write-operations.html["Separação de pools de conexão HTTP para operações de leitura e gravação"]

