---
permalink: s3/operations-on-objects.html 
sidebar: sidebar 
keywords: bucket, buckets, operations on buckets 
summary: Esta seção descreve como o sistema StorageGRID implementa S3 operações de API REST para objetos. 
---
= Operações em objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta seção descreve como o sistema StorageGRID implementa S3 operações de API REST para objetos.

* link:using-s3-object-lock.html["Usando S3 Object Lock"]
* link:using-server-side-encryption.html["Usando criptografia do lado do servver"]
* link:get-object.html["Objeto GET"]
* link:head-object.html["Objeto HEAD"]
* link:post-object-restore.html["Restauração PÓS-objeto"]
* link:put-object.html["Objeto PUT"]
* link:put-object-copy.html["COLOCAR Objeto - Copiar"]


As seguintes condições se aplicam a todas as operações de objetos:

* Os controles de consistência do StorageGRID são suportados por todas as operações em objetos, com exceção do seguinte:
+
** OBTER ACL Objeto
** `OPTIONS /`
** COLOCAR guarda legal Objeto
** COLOCAR retenção Objeto


* As solicitações de clientes conflitantes, como dois clientes escrevendo para a mesma chave, são resolvidas com base em "últimos ganhos". O calendário para a avaliação "últimos ganhos" é baseado em quando o sistema StorageGRID completa uma determinada solicitação e não em quando os clientes S3 começam uma operação.
* Todos os objetos em um bucket do StorageGRID são de propriedade do proprietário do bucket, incluindo objetos criados por um usuário anônimo ou por outra conta.
* Os objetos de dados ingeridos para o sistema StorageGRID através do Swift não podem ser acedidos através do S3.


A tabela a seguir descreve como o StorageGRID implementa operações de objetos API REST do S3.

|===
| Operação | Implementação 


 a| 
Objeto DELETE
 a| 
Autenticação multifator (MFA) e o cabeçalho de resposta `x-amz-mfa` não são suportados.

Ao processar uma solicitação DE EXCLUSÃO de objetos, o StorageGRID tenta remover imediatamente todas as cópias do objeto de todos os locais armazenados. Se for bem-sucedido, o StorageGRID retornará uma resposta ao cliente imediatamente. Se todas as cópias não puderem ser removidas dentro de 30 segundos (por exemplo, porque um local está temporariamente indisponível), o StorageGRID coloca as cópias em fila para remoção e, em seguida, indica sucesso para o cliente.

*Controle de versão*

Para remover uma versão específica, o solicitante deve ser o proprietário do bucket e usar o `versionId` subrecurso. O uso deste subrecurso exclui permanentemente a versão. Se o `versionId` corresponder a um marcador de exclusão, o cabeçalho de resposta `x-amz-delete-marker` será retornado como `true`.

* Se um objeto for excluído sem o `versionId` subrecurso em um bucket habilitado para versão, isso resultará na geração de um marcador de exclusão. O `versionId` para o marcador de exclusão é retornado usando o `x-amz-version-id` cabeçalho de resposta e o `x-amz-delete-marker` cabeçalho de resposta é retornado como `true`.
* Se um objeto for excluído sem o `versionId` sub-recurso em um bucket suspenso de versão, ele resultará em uma exclusão permanente de uma versão 'null' já existente ou um marcador 'null' delete, e a geração de um novo marcador 'null' delete. O `x-amz-delete-marker` cabeçalho de resposta é retornado definido como `true`.


*Nota*: Em certos casos, vários marcadores de exclusão podem existir para um objeto.



 a| 
Excluir vários objetos
 a| 
Autenticação multifator (MFA) e o cabeçalho de resposta `x-amz-mfa` não são suportados.

Vários objetos podem ser excluídos na mesma mensagem de solicitação.



 a| 
ELIMINAR marcação Objeto
 a| 
Usa o `tagging` subrecurso para remover todas as tags de um objeto. Implementado com todo o comportamento da API REST do Amazon S3.

*Controle de versão*

Se o `versionId` parâmetro de consulta não for especificado na solicitação, a operação excluirá todas as tags da versão mais recente do objeto em um bucket com versão. Se a versão atual do objeto for um marcador de exclusão, um status "'MethodNotAllowed'" será retornado com o `x-amz-delete-marker` cabeçalho de resposta definido como `true`.



 a| 
Objeto GET
 a| 
link:get-object.html["Objeto GET"]



 a| 
OBTER ACL Objeto
 a| 
Se as credenciais de acesso necessárias forem fornecidas para a conta, a operação retornará uma resposta positiva e a ID, DisplayName e permissão do proprietário do objeto, indicando que o proprietário tem acesso total ao objeto.



 a| 
OBTER retenção legal Objeto
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Usando S3 Object Lock"]



 a| 
OBTER retenção de objetos
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Usando S3 Object Lock"]



 a| 
OBTER marcação de objetos
 a| 
Usa o `tagging` subrecurso para retornar todas as tags para um objeto. Implementado com todo o comportamento da API REST do Amazon S3

*Controle de versão*

Se o `versionId` parâmetro de consulta não for especificado na solicitação, a operação retornará todas as tags da versão mais recente do objeto em um bucket versionado. Se a versão atual do objeto for um marcador de exclusão, um status "'MethodNotAllowed'" será retornado com o `x-amz-delete-marker` cabeçalho de resposta definido como `true`.



 a| 
Objeto HEAD
 a| 
link:head-object.html["Objeto HEAD"]



 a| 
Restauração PÓS-objeto
 a| 
link:post-object-restore.html["Restauração PÓS-objeto"]



 a| 
Objeto PUT
 a| 
link:put-object.html["Objeto PUT"]



 a| 
COLOCAR Objeto - Copiar
 a| 
link:put-object-copy.html["COLOCAR Objeto - Copiar"]



 a| 
COLOCAR guarda legal Objeto
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Usando S3 Object Lock"]



 a| 
COLOCAR retenção Objeto
 a| 
link:s3-rest-api-supported-operations-and-limitations.html["Usando S3 Object Lock"]



 a| 
COLOQUE a marcação Objeto
 a| 
Usa o `tagging` subrecurso para adicionar um conjunto de tags a um objeto existente. Implementado com todo o comportamento da API REST do Amazon S3

*Atualizações de tags e comportamento de ingestão*

Quando você usa a marcação "COLOCAR objeto" para atualizar as tags de um objeto, o StorageGRID não reingere o objeto. Isso significa que a opção de comportamento de ingestão especificada na regra ILM correspondente não é usada. Quaisquer alterações no posicionamento de objetos que são acionadas pela atualização são feitas quando o ILM é reavaliado por processos normais de ILM em segundo plano.

Isso significa que, se a regra ILM usar a opção estrita para o comportamento de ingestão, nenhuma ação será tomada se os posicionamentos de objeto necessários não puderem ser feitos (por exemplo, porque um local recém-exigido não está disponível). O objeto atualizado mantém seu posicionamento atual até que o posicionamento necessário seja possível.

*Resolução de conflitos*

As solicitações de clientes conflitantes, como dois clientes escrevendo para a mesma chave, são resolvidas com base em "últimos ganhos". O calendário para a avaliação "últimos ganhos" é baseado em quando o sistema StorageGRID completa uma determinada solicitação e não em quando os clientes S3 começam uma operação.

*Controle de versão*

Se o `versionId` parâmetro de consulta não for especificado na solicitação, a operação adicionará tags à versão mais recente do objeto em um bucket com versão. Se a versão atual do objeto for um marcador de exclusão, um status "'MethodNotAllowed'" será retornado com o `x-amz-delete-marker` cabeçalho de resposta definido como `true`.

|===
.Informações relacionadas
link:consistency-controls.html["Controles de consistência"]

link:s3-operations-tracked-in-audit-logs.html["S3 operações rastreadas nos logs de auditoria"]
