---
permalink: monitor/file-rotation-for-bycast-log.html 
sidebar: sidebar 
keywords: file rotation, bycast, log, file rotation, bycast.log 
summary: 'Quando o `bycast.log` arquivo atinge 1 GB, o arquivo existente é salvo e um novo arquivo de log é iniciado.' 
---
= Rotação de ficheiros para bycast.log
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o `bycast.log` arquivo atinge 1 GB, o arquivo existente é salvo e um novo arquivo de log é iniciado.

O arquivo salvo é renomeado `bycast.log.1` e o novo arquivo é `bycast.log` nomeado . Quando o novo `bycast.log` atinge 1 GB, `bycast.log.1` é renomeado e compactado para tornar `bycast.log.2.gz`, e `bycast.log` é renomeado `bycast.log.1`.

O limite de rotação para `bycast.log` é de 21 arquivos. Quando a versão 22nd do `bycast.log` arquivo é criada, o arquivo mais antigo é excluído.

O limite de rotação para `bycast-err.log` é de sete arquivos.


NOTE: Se um arquivo de log tiver sido compactado, você não deve descompactá-lo para o mesmo local em que foi escrito. A descompressão do arquivo para o mesmo local pode interferir com os scripts de rotação de log.

.Informações relacionadas
link:collecting-log-files-and-system-data.html["Coletando arquivos de log e dados do sistema"]
