---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords:  
summary: As mensagens de auditoria podem ajudá-lo a entender melhor as operações detalhadas do seu sistema StorageGRID. Você pode usar logs de auditoria para solucionar problemas e avaliar o desempenho. 
---
= Rever mensagens de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens de auditoria podem ajudá-lo a entender melhor as operações detalhadas do seu sistema StorageGRID. Você pode usar logs de auditoria para solucionar problemas e avaliar o desempenho.

Durante a operação normal do sistema, todos os serviços StorageGRID geram mensagens de auditoria, como segue:

* As mensagens de auditoria do sistema estão relacionadas ao próprio sistema de auditoria, aos estados dos nós da grade, à atividade de tarefas em todo o sistema e às operações de backup de serviço.
* As mensagens de auditoria de storage de objetos estão relacionadas ao armazenamento e gerenciamento de objetos no StorageGRID, incluindo armazenamento de objetos e recuperações, transferências de nó de grade para nó de grade e verificações.
* As mensagens de auditoria de leitura e gravação do cliente são registradas quando um aplicativo cliente S3 ou Swift faz uma solicitação para criar, modificar ou recuperar um objeto.
* As mensagens de auditoria de gerenciamento Registram solicitações de usuários para a API de gerenciamento.


Cada nó Admin armazena mensagens de auditoria em arquivos de texto. O compartilhamento de auditoria contém o arquivo ativo (audit.log), bem como logs de auditoria compatados de dias anteriores.

Para facilitar o acesso aos logs de auditoria, você pode configurar o acesso do cliente ao compartilhamento de auditoria para NFS e CIFS (obsoleto). Você também pode acessar arquivos de log de auditoria diretamente da linha de comando do nó Admin.

Para obter detalhes sobre o arquivo de log de auditoria, o formato das mensagens de auditoria, os tipos de mensagens de auditoria e as ferramentas disponíveis para analisar mensagens de auditoria, consulte as instruções para mensagens de auditoria. Para saber como configurar o acesso de cliente de auditoria, consulte as instruções para administrar o StorageGRID.

.Informações relacionadas
link:../audit/index.html["Rever registos de auditoria"]

link:../admin/index.html["Administrar o StorageGRID"]
