---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, adding interfaces, add interfaces, adding interface to node, add interface to node 
summary: Se você quiser adicionar uma interface a um nó baseado em Linux que você não instalou inicialmente, você deve usar este procedimento. 
---
= Linux: Adicionando interfaces a um nó existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser adicionar uma interface a um nó baseado em Linux que você não instalou inicialmente, você deve usar este procedimento.

Se você não configurou ADMIN_network_TARGET ou CLIENT_network_TARGET no arquivo de configuração do nó no host Linux durante a instalação, use este procedimento para adicionar a interface. Para obter mais informações sobre o arquivo de configuração do nó, consulte as instruções de instalação do StorageGRID para seu sistema operacional Linux.

link:../rhel/index.html["Instale o Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Instale Ubuntu ou Debian"]

Você executa este procedimento no servidor Linux que hospeda o nó que precisa da nova atribuição de rede, não dentro do nó. Este procedimento adiciona apenas a interface ao nó; ocorre um erro de validação se tentar especificar quaisquer outros parâmetros de rede.

Para fornecer informações de endereçamento, você deve usar a ferramenta alterar IP. Consulte as informações sobre como alterar a configuração de rede de um nó.

link:changing-nodes-network-configuration.html["Alterar a configuração de rede de um nó"]

.Passos
. Faça login no servidor Linux que hospeda o nó que precisa da nova atribuição de rede.
. Edite o arquivo de configuração do nó em `/etc/storagegrid/nodes/_node-name_.conf`.
+

IMPORTANT: Não especifique quaisquer outros parâmetros de rede, ou um erro de validação resultará.

+
.. Adicione o novo destino de rede.
+
[listing]
----
CLIENT_NETWORK_TARGET = bond0.3206
----
.. Opcional: Adicione um endereço MAC.
+
[listing]
----
CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c
----


. Execute o comando Node Validate: `sudo storagegrid node validate _node-name_`
. Resolva todos os erros de validação.
. Execute o comando node reload: `sudo storagegrid node reload _node-name_`


.Informações relacionadas
link:../rhel/index.html["Instale o Red Hat Enterprise Linux ou CentOS"]

link:../ubuntu/index.html["Instale Ubuntu ou Debian"]

link:changing-nodes-network-configuration.html["Alterar a configuração de rede de um nó"]
