---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords:  
summary: Talvez seja necessário aplicar um hotfix ao seu sistema StorageGRID se problemas com o software forem detetados e resolvidos entre versões de recursos. 
---
= Procedimento de correção do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário aplicar um hotfix ao seu sistema StorageGRID se problemas com o software forem detetados e resolvidos entre versões de recursos.

Os hotfixes do StorageGRID contêm alterações de software que são disponibilizadas fora de uma versão de recurso ou patch. As mesmas alterações estão incluídas em uma versão futura. Além disso, cada versão de hotfix contém um roll-up de todos os hotfixes anteriores dentro da versão de recurso ou patch.

* link:considerations-for-applying-hotfix.html["Considerações para aplicar um hotfix"]
* link:how-your-system-is-affected-when-you-apply-hotfix.html["Como seu sistema é afetado quando você aplica um hotfix"]
* link:obtaining-required-materials-for-hotfix.html["Obter os materiais necessários para um hotfix"]
* link:downloading-hotfix-file.html["Transferir o ficheiro de correção"]
* link:checking-systems-condition-before-applying-hotfix.html["Verificar a condição do sistema antes de aplicar um hotfix"]
* link:applying-hotfix.html["Aplicando o hotfix"]

