---
permalink: sg5700/configuring-hardware-sg5712-60.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Depois de aplicar energia ao dispositivo, você deve configurar o Gerenciador de sistema do SANtricity, que é o software que você usará para monitorar o hardware. Você também deve configurar as conexões de rede que serão usadas pelo StorageGRID. 
---
= Configurar o hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de aplicar energia ao dispositivo, você deve configurar o Gerenciador de sistema do SANtricity, que é o software que você usará para monitorar o hardware. Você também deve configurar as conexões de rede que serão usadas pelo StorageGRID.

.Passos
* link:configuring-storagegrid-connections.html["Configurando conexões StorageGRID"]
* link:accessing-and-configuring-santricity-system-manager.html["Acessando e configurando o Gerenciador do sistema do SANtricity"]
* link:optional-enabling-node-encryption.html["Opcional: Habilitando a criptografia de nó"]
* link:optional-changing-raid-mode-sg5760-only.html["Opcional: Alterar o modo RAID (apenas SG5760)"]
* link:optional-remapping-network-ports-for-appliance-sg5600-and-sg5700.html["Opcional: Remapeamento de portas de rede para o dispositivo"]

