---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, node, site, add, adding, expand, expansion 
summary: Você pode seguir este procedimento para adicionar nós de grade a sites existentes ou adicionar um novo site, mas não pode executar ambos os tipos de expansão ao mesmo tempo. 
---
= Adicionar nós de grade a um site existente ou adicionar um novo site
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode seguir este procedimento para adicionar nós de grade a sites existentes ou adicionar um novo site, mas não pode executar ambos os tipos de expansão ao mesmo tempo.

.O que você vai precisar
* Você deve ter permissões de root ou manutenção. Para obter detalhes, consulte informações sobre como controlar o acesso ao sistema com contas e grupos de usuários de administração.
* Todos os nós existentes na grade devem estar ativos e em execução em todos os locais.
* Quaisquer procedimentos anteriores de expansão, atualização, desativação ou recuperação devem estar concluídos.
+

NOTE: Você é impedido de iniciar uma expansão enquanto outro procedimento de expansão, atualização, recuperação ou desativação ativa está em andamento. No entanto, se necessário, você pode pausar um procedimento de desativação para iniciar uma expansão.



.Passos
. link:updating-subnets-for-grid-network.html["Atualizando sub-redes para a rede de Grade"]
. link:deploying-new-grid-nodes.html["Implantando novos nós de grade"]
. link:performing-expansion.html["Executando a expansão"]

