---
permalink: expand/configuring-expanded-storagegrid-system.html 
sidebar: sidebar 
keywords: expansion, configuration 
summary: Depois de concluir uma expansão, você deve executar etapas adicionais de integração e configuração. 
---
= Configurando seu sistema StorageGRID expandido
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de concluir uma expansão, você deve executar etapas adicionais de integração e configuração.

.Sobre esta tarefa
Você deve concluir as tarefas de configuração listadas abaixo para os nós de grade que você está adicionando em sua expansão. Algumas tarefas podem ser opcionais, dependendo das opções selecionadas durante a instalação e administração do sistema, e como você deseja configurar os nós de grade adicionados durante a expansão.

.Passos
. Se você adicionou um nó de storage, execute as seguintes tarefas de configuração.
+
[cols="2a,1a"]
|===
| Tarefas de configuração do nó de storage | Para obter informações 


 a| 
Revise os pools de armazenamento usados em suas regras de ILM para garantir que o novo armazenamento será usado.

** Se você adicionou um site, crie um pool de armazenamento para o site e atualize as regras do ILM para usar o novo pool de armazenamento.
** Se você adicionou um nó de armazenamento a um site existente, confirme se o novo nó usa o grau de armazenamento correto.
+
*Observação:* por padrão, um novo nó de armazenamento é atribuído ao nível de armazenamento de todos os nós de armazenamento e adicionado a pools de armazenamento que usam essa classificação para o site. Se você quiser que um novo nó use um grau de armazenamento personalizado, você deve atribuí-lo manualmente ao grau personalizado (*ILM* > *graus de armazenamento*).


 a| 
link:../ilm/index.html["Gerenciar objetos com ILM"]



 a| 
Verifique se o nó de armazenamento está ingerindo objetos.
 a| 
link:verifying-storage-node-is-active.html["Verificando se o nó de storage está ativo"]



 a| 
Rebalancear os dados codificados por apagamento (somente se você não conseguir adicionar o número recomendado de nós de storage).
 a| 
link:rebalancing-erasure-coded-data-after-adding-storage-nodes.html["Rebalanceamento de dados codificados por apagamento após a adição de nós de storage"]

|===
. Se você adicionou um nó de gateway, execute as seguintes tarefas de configuração.
+
[cols="2a,1a"]
|===
| Tarefas de configuração do Gateway Node | Para obter informações 


 a| 
Se forem utilizados grupos de alta disponibilidade para ligações de clientes, adicione os nós de Gateway a um grupo de HA. Selecione *Configuração* > *Configurações de rede* > *grupos de alta disponibilidade* para revisar a lista de grupos de HA existentes e adicionar os novos nós.
 a| 
link:../admin/index.html["Administrar o StorageGRID"]

|===
. Se você adicionou um nó Admin, execute as seguintes tarefas de configuração.
+
[cols="2a,1a"]
|===
| Tarefas de configuração do nó de administração | Para obter informações 


 a| 
Se o logon único estiver ativado para o seu sistema StorageGRID, você deverá criar uma confiança de parte confiável nos Serviços de Federação do ative Directory (AD FS) para o novo nó de administração. Você não pode entrar no nó até criar essa confiança de parte confiável.
 a| 
link:../admin/configuring-sso.html["Configurando logon único"]



 a| 
Se você planeja usar o serviço Load Balancer em nós de administração, talvez seja necessário adicionar os nós de administração a grupos de alta disponibilidade. Selecione *Configuração* > *Configurações de rede* > *grupos de alta disponibilidade* para revisar a lista de grupos de HA existentes e adicionar os novos nós.
 a| 
link:../admin/index.html["Administrar o StorageGRID"]



 a| 
Opcionalmente, copie o banco de dados do nó Admin do nó Admin principal para o nó Admin de expansão se quiser manter as informações de atributo e auditoria consistentes em cada nó Admin.
 a| 
link:copying-admin-node-database.html["Copiando o banco de dados Admin Node"]



 a| 
Opcionalmente, copie o banco de dados Prometheus do nó Admin primário para o nó Admin de expansão se quiser manter as métricas históricas consistentes em cada nó Admin.
 a| 
link:copying-prometheus-metrics.html["Copiando métricas Prometheus"]



 a| 
Opcionalmente, copie os logs de auditoria existentes do nó de administração principal para o nó de administração de expansão se quiser manter as informações de log histórico consistentes em cada nó de administração.
 a| 
link:copying-audit-logs.html["Copiar registos de auditoria"]



 a| 
Opcionalmente, configure o acesso ao sistema para fins de auditoria por meio de um compartilhamento de arquivos NFS ou CIFS.

*Observação:* a exportação de auditoria por meio do CIFS/Samba foi obsoleta e será removida em uma futura versão do StorageGRID.
 a| 
link:../admin/index.html["Administrar o StorageGRID"]



 a| 
Opcionalmente, altere o remetente preferido para notificações. Você pode tornar o nó de administração de expansão o remetente preferido. Caso contrário, um nó de administração existente configurado como o remetente preferido continua a enviar notificações, incluindo mensagens AutoSupport, notificações SNMP, e-mails de alerta e e-mails de alarme (sistema legado).
 a| 
link:../admin/index.html["Administrar o StorageGRID"]

|===
. Se tiver adicionado um nó de arquivo, conclua as seguintes tarefas de configuração.
+
[cols="2a,1a"]
|===
| Tarefas de configuração do nó de arquivamento | Para obter informações 


 a| 
Configure a ligação do nó de arquivo ao sistema de armazenamento de arquivo externo de destino. Quando você conclui a expansão, os nós de arquivo estão em um estado de alarme até que você configure as informações de conexão através do componente *ARC* > *Target*.
 a| 
link:../admin/index.html["Administrar o StorageGRID"]



 a| 
Atualize a política ILM para arquivar dados de objetos através do novo nó de arquivo.
 a| 
link:../ilm/index.html["Gerenciar objetos com ILM"]



 a| 
Configure alarmes personalizados para os atributos usados para monitorar a velocidade e a eficiência da recuperação de dados de objetos a partir de nós de arquivo.
 a| 
link:../admin/index.html["Administrar o StorageGRID"]

|===
. Para verificar se os nós de expansão foram adicionados a uma rede cliente não confiável ou para alterar se a rede cliente de um nó não é confiável ou confiável, vá para *Configuração* > *Configurações de rede* > *rede cliente não confiável*.
+
Se a rede do cliente no nó de expansão não for confiável, as conexões com o nó na rede do cliente devem ser feitas usando um ponto de extremidade do balanceador de carga. Consulte as instruções para administrar o StorageGRID para obter mais informações.

. Configure o sistema de nomes de domínio (DNS).
+
Se você tiver especificado as configurações de DNS separadamente para cada nó de grade, você deve adicionar configurações de DNS personalizadas por nó para os novos nós. Consulte informações sobre como modificar a configuração DNS para um único nó de grade nas instruções de recuperação e manutenção.

+
A melhor prática é que a lista de servidores DNS em toda a grade contenha alguns servidores DNS que são acessíveis localmente a partir de cada site. Se você acabou de adicionar um novo site, adicione novos servidores DNS para o site à configuração DNS em toda a grade.

+

IMPORTANT: Forneça dois a seis endereços IPv4 para servidores DNS. Você deve selecionar servidores DNS que cada site pode acessar localmente no caso de rede ser aterrissada. Isso é para garantir que um site islanded continua a ter acesso ao serviço DNS. Depois de configurar a lista de servidores DNS em toda a grade, você pode personalizar ainda mais a lista de servidores DNS para cada nó. Para obter detalhes, consulte as informações sobre como modificar a configuração DNS nas instruções de recuperação e manutenção.

. Se você adicionou um novo site, confirme se os servidores NTP (Network Time Protocol) estão acessíveis a partir desse site.
+

IMPORTANT: Certifique-se de que pelo menos dois nós em cada local possam acessar pelo menos quatro fontes NTP externas. Se apenas um nó em um local puder alcançar as fontes NTP, problemas de tempo ocorrerão se esse nó cair. Além disso, a designação de dois nós por local como fontes primárias de NTP garante um tempo preciso se um local for isolado do resto da grade.

+
Para obter mais informações, consulte as instruções de recuperação e manutenção.



.Informações relacionadas
link:../ilm/index.html["Gerenciar objetos com ILM"]

link:verifying-storage-node-is-active.html["Verificando se o nó de storage está ativo"]

link:copying-admin-node-database.html["Copiando o banco de dados Admin Node"]

link:copying-prometheus-metrics.html["Copiando métricas Prometheus"]

link:copying-audit-logs.html["Copiar registos de auditoria"]

link:../upgrade/index.html["Atualizar o software"]

link:../maintain/index.html["Manter  recuperar"]
