---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: Quando você adiciona um novo nó Admin por meio de um procedimento de expansão, seu serviço AMS somente Registra eventos e ações que ocorrem depois que ele se une ao sistema. Você pode copiar logs de auditoria de um nó de administrador instalado anteriormente para o novo nó de administrador de expansão, de modo que ele esteja sincronizado com o resto do sistema StorageGRID. 
---
= Copiar registos de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você adiciona um novo nó Admin por meio de um procedimento de expansão, seu serviço AMS somente Registra eventos e ações que ocorrem depois que ele se une ao sistema. Você pode copiar logs de auditoria de um nó de administrador instalado anteriormente para o novo nó de administrador de expansão, de modo que ele esteja sincronizado com o resto do sistema StorageGRID.

.O que você vai precisar
* Você deve ter concluído as etapas de expansão necessárias para adicionar um nó de administrador.
* Tem de ter o `Passwords.txt` ficheiro.


.Sobre esta tarefa
Para disponibilizar as mensagens de auditoria histórica de outros nós de administração no nó de administração de expansão, você deve copiar os arquivos de log de auditoria manualmente do nó de administração principal ou de outro nó de administração existente para o nó de administração de expansão.

.Passos
. Faça login no nó de administração principal:
+
.. Introduza o seguinte comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Pare o serviço AMS para impedir que ele crie um novo arquivo: `service ams stop`
. Renomeie `audit.log` o arquivo para garantir que ele não substitua o arquivo no nó de administração de expansão para o qual você está copiando:
+
`cd /var/local/audit/export`
`ls -l` E
`mv audit.log _new_name_.txt`

. Copiar todos os arquivos de log de auditoria para o nó de administração de expansão:
+
`scp -p * _IP_address_:/var/local/audit/export`

. Se for solicitada a senha para `/root/.ssh/id_rsa`, digite a senha de acesso SSH para o nó de administração principal listado no `Passwords.txt` arquivo.
. Restaure o arquivo original `audit.log`:
+
`mv _new_name_.txt audit.log`

. Inicie o serviço AMS:
+
`service ams start`

. Terminar sessão a partir do servidor:
+
`exit`

. Faça login no nó de administração de expansão:
+
.. Introduza o seguinte comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.



. Atualize as configurações de usuário e grupo para os arquivos de log de auditoria:
+
`cd /var/local/audit/export` E
`chown ams-user:bycast *`

. Terminar sessão a partir do servidor:
+
`exit`


