---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines 
summary: Você pode expandir a capacidade de storage de objetos do seu sistema StorageGRID adicionando volumes de storage a nós de storage existentes ou adicionando novos nós de storage a locais existentes. Você deve adicionar capacidade de armazenamento de uma forma que atenda aos requisitos da política de gerenciamento do ciclo de vida das informações. 
---
= Diretrizes para adicionar capacidade de objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode expandir a capacidade de storage de objetos do seu sistema StorageGRID adicionando volumes de storage a nós de storage existentes ou adicionando novos nós de storage a locais existentes. Você precisa adicionar capacidade de storage de forma que atenda aos requisitos da política de gerenciamento do ciclo de vida das informações (ILM).



== Diretrizes para adicionar volumes de armazenamento

Antes de adicionar volumes de storage a nós de storage existentes, consulte as diretrizes e limitações a seguir:

* Você deve examinar suas regras atuais de ILM para determinar onde e quando adicionar volumes de storage para aumentar o storage disponível para objetos replicados ou codificados por apagamento. Consulte as instruções para gerenciar objetos com gerenciamento do ciclo de vida das informações.
* Você não pode aumentar a capacidade de metadados do sistema adicionando volumes de storage porque os metadados de objetos são armazenados apenas no volume 0.
* Cada nó de storage baseado em software pode dar suporte a um máximo de 16 volumes de storage. Se você precisar adicionar capacidade além disso, precisará adicionar novos nós de storage.
* Você pode adicionar uma ou duas gavetas de expansão a cada dispositivo SG6060. Cada compartimento de expansão adiciona 16 volumes de storage. Com ambas as gavetas de expansão instaladas, o SG6060 dá suporte a um total de 48 volumes de storage.
* Não é possível adicionar volumes de armazenamento a qualquer outro dispositivo de armazenamento.
* Não é possível aumentar o tamanho de um volume de armazenamento existente.
* Não é possível adicionar volumes de armazenamento a um nó de armazenamento ao mesmo tempo em que está a efetuar uma atualização do sistema, uma operação de recuperação ou outra expansão.


Depois de decidir adicionar volumes de storage e determinar quais nós de storage você deve expandir para atender à política de ILM, siga as instruções para seu tipo de nó de storage:

* Para adicionar prateleiras de expansão a um dispositivo de armazenamento SG6060, consulte as instruções para a instalação e manutenção do dispositivo SG6000.
+
link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

* Para um nó baseado em software, siga as instruções para adicionar volumes de storage aos nós de storage.
+
link:adding-storage-volumes-to-storage-nodes.html["Adição de volumes de storage aos nós de storage"]





== Diretrizes para a adição de nós de storage

Antes de adicionar nós de storage a sites existentes, consulte as diretrizes e limitações a seguir:

* Você deve examinar suas regras atuais de ILM para determinar onde e quando adicionar nós de storage para aumentar o storage disponível para objetos replicados ou codificados por apagamento.
* Você não deve adicionar mais de 10 nós de storage em um único procedimento de expansão.
* Você pode adicionar nós de storage a mais de um local em um único procedimento de expansão.
* Você pode adicionar nós de storage e outros tipos de nós em um único procedimento de expansão.
* Antes de iniciar o procedimento de expansão, deve confirmar se todas as operações de reparação de dados efetuadas como parte de uma recuperação estão concluídas. Consulte os passos para verificar os trabalhos de reparação de dados nas instruções de recuperação e manutenção.
* Se você precisar remover nós de storage antes ou depois de executar uma expansão, não deverá desativar mais de 10 nós de storage em um único procedimento de nó de compactação.




== Diretrizes para o serviço ADC em nós de storage

Ao configurar a expansão, você deve escolher se deseja incluir o serviço controlador de domínio administrativo (ADC) em cada novo nó de armazenamento. O serviço ADC mantém o controle da localização e disponibilidade dos serviços da grade.

* O sistema StorageGRID requer que um quórum de serviços ADC esteja disponível em cada local e em todos os momentos.
+

NOTE: Saiba mais sobre o quórum ADC nas instruções de recuperação e manutenção.

* Pelo menos três nós de storage em cada local devem incluir o serviço ADC.
* Adicionar o serviço ADC a cada nó de armazenamento não é recomendado. Incluir muitos serviços ADC pode causar lentidão devido ao aumento da quantidade de comunicação entre nós.
* Uma única grade não deve ter mais de 48 nós de storage com o serviço ADC. Isso equivale a 16 sites com três serviços ADC em cada local.
* Em geral, quando você seleciona a configuração *ADC Service* para um novo nó, você deve selecionar *Automatic*. Selecione *Sim* somente se o novo nó substituir outro nó de armazenamento que inclua o serviço ADC. Como você não pode desativar um nó de armazenamento se houver poucos serviços ADC, isso garante que um novo serviço ADC esteja disponível antes que o serviço antigo seja removido.
* Você não pode adicionar o serviço ADC a um nó depois que ele é implantado.


*Informações relacionadas*

link:../ilm/index.html["Gerenciar objetos com ILM"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:adding-storage-volumes-to-storage-nodes.html["Adição de volumes de storage aos nós de storage"]

link:../maintain/index.html["Manter  recuperar"]

link:performing-expansion.html["Executando a expansão"]
