---
permalink: fabricpool/creating-tenant-account-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, tenant, SSO 
summary: Você deve criar uma conta de locatário no Gerenciador de Grade para uso do FabricPool. 
---
= Criando uma conta de locatário para o FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar uma conta de locatário no Gerenciador de Grade para uso do FabricPool.

.O que você vai precisar
* Você deve estar conetado ao Gerenciador de Grade usando um navegador compatível.
* Você deve ter permissões de acesso específicas.


.Sobre esta tarefa
As contas de inquilino permitem que aplicativos clientes armazenem e recuperem objetos no StorageGRID. Cada conta de locatário tem seu próprio ID de conta, grupos e usuários autorizados, buckets e objetos.

Você pode usar a mesma conta de locatário para vários clusters do ONTAP. Ou você pode criar uma conta de locatário dedicada para cada cluster do ONTAP, conforme necessário.

[NOTE]
====
Essas instruções assumem que você configurou logon único (SSO) para o Gerenciador de Grade. Se você não estiver usando SSO, use as instruções para link:../admin/creating-tenant-account-if-storagegrid-is-not-using-sso.html["Criando uma conta de locatário se o StorageGRID não estiver usando SSO"].

====
.Passos
. Selecione *tenants*.
. Selecione *criar*.
. Insira um nome de exibição para a conta de locatário do FabricPool.
. Selecione *S3*.
. Deixe a caixa de seleção *permitir Serviços de Plataforma* selecionada para habilitar o uso de serviços de plataforma.
+
Se os serviços de plataforma estiverem ativados, um locatário poderá usar recursos, como a replicação do CloudMirror, que acessam serviços externos.

. Deixe o campo *cota de armazenamento* em branco.
. No campo *Root Access Group*, selecione um grupo federado existente no Gerenciador de Grade para ter a permissão de acesso raiz inicial para o locatário.
. Selecione *Guardar*.

