---
permalink: fabricpool/example-ilm-policy-for-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ilm, information lifecycle management, ILM policy, example 
summary: Use esta política de exemplo simples como ponto de partida para suas próprias regras e políticas ILM. 
---
= Exemplo de política de ILM para dados do FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use esta política de exemplo simples como ponto de partida para suas próprias regras e políticas ILM.

Este exemplo pressupõe que você esteja projetando as regras de ILM e uma política de ILM para um sistema StorageGRID que tenha quatro nós de storage em um único data center em Denver, Colorado. Os dados do FabricPool neste exemplo usam um bucket `fabricpool-bucket` chamado .

[CAUTION]
====
As seguintes regras e políticas do ILM são apenas exemplos. Existem muitas maneiras de configurar regras ILM. Antes de ativar uma nova política, simule a política proposta para confirmar que ela funcionará como a intenção de proteger o conteúdo contra perda.

Para saber mais: link:../ilm/index.html["Gerenciar objetos com ILM"]

====
.Passos
. Crie um pool de armazenamento chamado *DEN*. Selecione o site de Denver.
. Crie um perfil de codificação de apagamento chamado *2 plus 1*. Selecione o esquema de codificação de apagamento 2-1 e o pool de armazenamento *DEN*.
. Crie uma regra ILM que se aplique apenas aos dados no `fabricpool-bucket`. esta regra de exemplo cria cópias codificadas por apagamento.
+
[cols="1a,1a"]
|===
| Definição de regra | Exemplo de valor 


 a| 
Nome da regra
 a| 
Codificação de apagamento 2 mais 1 para dados FabricPool



 a| 
Nome do balde
 a| 
`fabricpool-bucket`

Você também pode filtrar na conta de locatário do FabricPool.



 a| 
Filtragem avançada
 a| 
Tamanho do objeto (MB) superior a 0,2 MB.

*Observação:* o FabricPool só grava objetos de 4 MB, mas você deve adicionar um filtro de tamanho de objeto porque essa regra usa codificação de apagamento.



 a| 
Tempo de referência
 a| 
Tempo de ingestão



 a| 
Colocação
 a| 
Desde o dia 0 loja para sempre



 a| 
Tipo
 a| 
Codificar para apagamento



 a| 
Localização
 a| 
DEN (2 mais 1)



 a| 
Comportamento de ingestão
 a| 
Equilibrado

|===
. Crie uma regra ILM que criará duas cópias replicadas de quaisquer objetos não correlacionados com a primeira regra. Não selecione um filtro básico (conta de locatário ou nome do bucket) ou quaisquer filtros avançados.
+
[cols="1a,1a"]
|===
| Definição de regra | Exemplo de valor 


 a| 
Nome da regra
 a| 
Duas cópias replicadas



 a| 
Nome do balde
 a| 
_none_



 a| 
Filtragem avançada
 a| 
_none_



 a| 
Tempo de referência
 a| 
Tempo de ingestão



 a| 
Colocação
 a| 
Desde o dia 0 loja para sempre



 a| 
Tipo
 a| 
Replicado



 a| 
Localização
 a| 
DEN



 a| 
Cópias
 a| 
2



 a| 
Comportamento de ingestão
 a| 
Equilibrado

|===
. Crie uma política de ILM proposta e selecione as duas regras. Como a regra de replicação não usa filtros, ela pode ser a regra padrão (última) para a política.
. Ingira objetos de teste na grade.
. Simule a política com os objetos de teste para verificar o comportamento.
. Ative a política.


Quando esta política é ativada, o StorageGRID coloca os dados de objeto da seguinte forma:

* Os dados dispostos em camadas em FabricPool in `fabricpool-bucket` serão codificados para apagamento usando o esquema de codificação de apagamento 2-1. Dois fragmentos de dados e um fragmento de paridade serão colocados em três nós de storage diferentes.
* Todos os objetos em todos os outros buckets serão replicados. Duas cópias serão criadas e colocadas em dois nós de storage diferentes.
* As cópias codificadas por apagamento e replicadas serão mantidas no StorageGRID até que sejam excluídas pelo cliente S3. StorageGRID ILM nunca excluirá esses itens.

